"""Function theory generated by Addition (A) and Multiplication (M).

Mathematical lineage
--------------------
Ordinary calculus is usually taught after the additive coordinate line has
already been chosen: translation is invisible background structure, and
multiplication appears later as a nonlinear operation on numbers or functions.
The AEG/Shakespeare reconstruction asks what changes if Addition and
Multiplication themselves are treated as primitive process directions before a
function theory is chosen.

At finite scale the two processes are

    T_t: (a, v) -> (a + t, v),
    S_s: (a, v) -> (exp(s) * a, v + s),

and their history is noncommutative:

    S_s T_t = T_(exp(s) t) S_s.

The infinitesimal shadow is therefore not two arbitrary differential operators
but the arithmetic frame

    A = d/da,
    M = d/dv + a d/da,

with ``[A, M] = A``. Function families are then judged by how simply they
transform under these process histories. The power-weight lattice is one such
family; process inversion exposes resonance loci, and those loci force
logarithmic or Jordan-like extensions rather than assuming ``log`` in advance.

Boundary
--------
A/M is the first concrete Shakespeare function theory, not the universal one.
"""

from __future__ import annotations

from dataclasses import dataclass

import sympy as sp

from ..process.local import ProcessFrame


def affine_am_frame(a: sp.Symbol, v: sp.Symbol) -> ProcessFrame:
    """Return the canonical Addition/Multiplication process frame."""
    return ProcessFrame(
        assignments=(a, v),
        generators={
            "A": {a: sp.S.One, v: sp.S.Zero},
            "M": {a: a, v: sp.S.One},
        },
    )


@dataclass(frozen=True)
class AMState:
    a: sp.Expr
    v: sp.Expr


@dataclass(frozen=True)
class AMPowerWeight:
    a: sp.Symbol
    v: sp.Symbol
    nu: sp.Expr
    weight: sp.Expr

    @property
    def expression(self) -> sp.Expr:
        return self.a ** self.nu * sp.exp((self.weight - self.nu) * self.v)

    def product(self, other: "AMPowerWeight") -> "AMPowerWeight":
        if self.a != other.a or self.v != other.v:
            raise ValueError("power-weight elements must use the same A/M coordinates")
        return AMPowerWeight(
            self.a,
            self.v,
            sp.simplify(self.nu + other.nu),
            sp.simplify(self.weight + other.weight),
        )


@dataclass(frozen=True)
class AMPrimitive:
    generator: str
    integrand: AMPowerWeight
    expression: sp.Expr
    resonant: bool
    exceptional_factor: sp.Expr


@dataclass(frozen=True)
class AMPathFlow:
    start: sp.Expr
    end: sp.Expr
    beta_integral: sp.Expr
    history_term: sp.Expr
    a_end: sp.Expr
    v_end: sp.Expr


@dataclass(frozen=True)
class AMFunctionTheory:
    """Concrete function calculus generated by Addition and Multiplication."""

    a: sp.Symbol
    v: sp.Symbol

    @property
    def frame(self) -> ProcessFrame:
        return affine_am_frame(self.a, self.v)

    def A(self, expr: sp.Expr) -> sp.Expr:
        return self.frame.apply("A", expr)

    def M(self, expr: sp.Expr) -> sp.Expr:
        return self.frame.apply("M", expr)

    def commutator(self, expr: sp.Expr) -> sp.Expr:
        return self.frame.commutator("A", "M", expr)

    def add(self, state: AMState, amount: sp.Expr) -> AMState:
        amount = sp.sympify(amount)
        return AMState(sp.expand(state.a + amount), sp.sympify(state.v))

    def multiply(self, state: AMState, log_scale: sp.Expr) -> AMState:
        log_scale = sp.sympify(log_scale)
        return AMState(
            sp.expand(sp.exp(log_scale) * state.a),
            sp.expand(state.v + log_scale),
        )

    def finite_relation_residual(
        self,
        state: AMState,
        *,
        amount: sp.Expr,
        log_scale: sp.Expr,
    ) -> tuple[sp.Expr, sp.Expr]:
        amount = sp.sympify(amount)
        log_scale = sp.sympify(log_scale)
        left = self.multiply(self.add(state, amount), log_scale)
        right = self.add(
            self.multiply(state, log_scale),
            sp.exp(log_scale) * amount,
        )
        return (
            sp.simplify(left.a - right.a),
            sp.simplify(left.v - right.v),
        )

    def power_weight(self, nu: sp.Expr, weight: sp.Expr) -> AMPowerWeight:
        return AMPowerWeight(self.a, self.v, sp.sympify(nu), sp.sympify(weight))

    def multiply_power_weights(
        self,
        left: AMPowerWeight,
        right: AMPowerWeight,
    ) -> AMPowerWeight:
        return left.product(right)

    def A_primitive(self, element: AMPowerWeight) -> AMPrimitive:
        if element.a != self.a or element.v != self.v:
            raise ValueError("power-weight element belongs to another A/M frame")
        exceptional = sp.simplify(element.nu + 1)
        if exceptional == 0:
            primitive = sp.exp((element.weight + 1) * self.v) * sp.log(self.a)
            return AMPrimitive(
                generator="A",
                integrand=element,
                expression=primitive,
                resonant=True,
                exceptional_factor=exceptional,
            )
        next_element = self.power_weight(element.nu + 1, element.weight + 1)
        return AMPrimitive(
            generator="A",
            integrand=element,
            expression=sp.simplify(next_element.expression / exceptional),
            resonant=False,
            exceptional_factor=exceptional,
        )

    def M_primitive(self, element: AMPowerWeight) -> AMPrimitive:
        if element.a != self.a or element.v != self.v:
            raise ValueError("power-weight element belongs to another A/M frame")
        exceptional = sp.simplify(element.weight)
        if exceptional == 0:
            return AMPrimitive(
                generator="M",
                integrand=element,
                expression=sp.expand(self.v * element.expression),
                resonant=True,
                exceptional_factor=exceptional,
            )
        return AMPrimitive(
            generator="M",
            integrand=element,
            expression=sp.simplify(element.expression / exceptional),
            resonant=False,
            exceptional_factor=exceptional,
        )

    def primitive_residual(self, primitive: AMPrimitive) -> sp.Expr:
        if primitive.generator == "A":
            image = self.A(primitive.expression)
        elif primitive.generator == "M":
            image = self.M(primitive.expression)
        else:
            raise ValueError(f"unknown A/M primitive generator: {primitive.generator!r}")
        return sp.simplify(sp.expand(image - primitive.integrand.expression))

    def shifted_M(self, expr: sp.Expr, shift: sp.Expr) -> sp.Expr:
        return sp.expand(self.M(expr) - sp.sympify(shift) * sp.sympify(expr))

    def pbw_residual(self, expr: sp.Expr, *, m: int, n: int) -> sp.Expr:
        if m < 0 or n < 0:
            raise ValueError("m and n must be non-negative")
        left = self.frame.iterate("A", expr, m)
        left = self.frame.iterate("M", left, n)
        right = sp.sympify(expr)
        for _ in range(n):
            right = self.shifted_M(right, m)
        right = self.frame.iterate("A", right, m)
        return sp.simplify(sp.expand(left - right))

    def path_flow(
        self,
        alpha: sp.Expr,
        beta: sp.Expr,
        time: sp.Symbol,
        *,
        start: sp.Expr,
        end: sp.Expr,
        a0: sp.Expr,
        v0: sp.Expr,
    ) -> AMPathFlow:
        alpha = sp.sympify(alpha)
        beta = sp.sympify(beta)
        start = sp.sympify(start)
        end = sp.sympify(end)
        a0 = sp.sympify(a0)
        v0 = sp.sympify(v0)

        tau = sp.Dummy("tau")
        sigma = sp.Dummy("sigma")
        beta_sigma = beta.subs(time, sigma)
        beta_integral = sp.integrate(beta_sigma, (sigma, start, end))
        beta_to_tau = sp.integrate(beta_sigma, (sigma, start, tau))
        alpha_tau = alpha.subs(time, tau)
        history_term = sp.integrate(
            sp.exp(beta_integral - beta_to_tau) * alpha_tau,
            (tau, start, end),
        )
        a_end = sp.simplify(sp.exp(beta_integral) * a0 + history_term)
        v_end = sp.simplify(v0 + beta_integral)
        return AMPathFlow(
            start=start,
            end=end,
            beta_integral=sp.simplify(beta_integral),
            history_term=sp.simplify(history_term),
            a_end=a_end,
            v_end=v_end,
        )
