"""Optional function theory generated by Addition (A) and Multiplication (M).

Here **A means Addition** and **M means Multiplication**.  They are the two
arithmetic process directions of the one-variable AEG construction, not names
for abstract moments or generic linear operators.

In logarithmic multiplicative coordinate ``v`` the infinitesimal generators are

    A = d/da,
    M = d/dv + a d/da,

so ``[A,M] = A``.  Their finite flows are ordinary addition and multiplication:

    T_t: (a,v) -> (a+t, v),
    S_s: (a,v) -> (exp(s)*a, v+s),

with the noncommutative relation

    S_s T_t = T_(exp(s)t) S_s.

This module packages the A/M-generated function theory as one concrete layer
above Shakespeare's generic process machinery.  It is deliberately not made
the universal ontology: projective, elliptic, hyperelliptic, Lie-algebroid, or
other process/function theories may coexist beside it.
"""

from __future__ import annotations

from dataclasses import dataclass

import sympy as sp

from ..frame import ProcessFrame


def affine_am_frame(a: sp.Symbol, v: sp.Symbol) -> ProcessFrame:
    """Return the canonical Addition/Multiplication process frame."""

    return ProcessFrame(
        assignments=(a, v),
        generators={
            "A": {a: sp.S.One, v: sp.S.Zero},
            "M": {a: a, v: sp.S.One},
        },
    )


@dataclass(frozen=True)
class AMState:
    """State coordinates for the finite Addition/Multiplication action."""

    a: sp.Expr
    v: sp.Expr


@dataclass(frozen=True)
class AMPowerWeight:
    """One member of the A/M power-weight family.

    The represented expression is

        Phi_(nu,w) = a**nu * exp((w-nu)*v).

    Under the Addition/Multiplication frame,

        M Phi_(nu,w) = w Phi_(nu,w),
        A Phi_(nu,w) = nu Phi_(nu-1,w-1).

    ``nu`` and ``weight`` are symbolic parameters; no claim is made that this
    family exhausts the A/M function theory, much less all possible Shakespeare
    function theories.
    """

    a: sp.Symbol
    v: sp.Symbol
    nu: sp.Expr
    weight: sp.Expr

    @property
    def expression(self) -> sp.Expr:
        return self.a ** self.nu * sp.exp((self.weight - self.nu) * self.v)


@dataclass(frozen=True)
class AMFunctionTheory:
    """Convenience wrapper for the Addition/Multiplication function calculus.

    This object intentionally sits *above* ``ProcessFrame``.  A/M is one
    arithmetic function-theory choice; Shakespeare's literal histories, task
    quotients, grammar discovery, and presentation search do not depend on it.
    """

    a: sp.Symbol
    v: sp.Symbol

    @property
    def frame(self) -> ProcessFrame:
        return affine_am_frame(self.a, self.v)

    def A(self, expr: sp.Expr) -> sp.Expr:
        """Apply the infinitesimal Addition generator."""

        return self.frame.apply("A", expr)

    def M(self, expr: sp.Expr) -> sp.Expr:
        """Apply the infinitesimal Multiplication generator."""

        return self.frame.apply("M", expr)

    def commutator(self, expr: sp.Expr) -> sp.Expr:
        """Return ``[A,M] expr``; in this frame it equals ``A(expr)``."""

        return self.frame.commutator("A", "M", expr)

    def add(self, state: AMState, amount: sp.Expr) -> AMState:
        """Finite Addition flow ``T_amount``."""

        amount = sp.sympify(amount)
        return AMState(sp.expand(state.a + amount), sp.sympify(state.v))

    def multiply(self, state: AMState, log_scale: sp.Expr) -> AMState:
        """Finite Multiplication flow ``S_log_scale``.

        ``log_scale`` is the additive coordinate of the multiplicative ruler;
        the physical scale factor is ``exp(log_scale)``.
        """

        log_scale = sp.sympify(log_scale)
        return AMState(
            sp.expand(sp.exp(log_scale) * state.a),
            sp.expand(state.v + log_scale),
        )

    def finite_relation_residual(
        self,
        state: AMState,
        *,
        amount: sp.Expr,
        log_scale: sp.Expr,
    ) -> tuple[sp.Expr, sp.Expr]:
        """Verify ``S_s T_t = T_(exp(s)t) S_s`` on one symbolic state.

        The returned pair is zero exactly when the finite Addition/Multiplication
        relation holds under the chosen symbolic backend.
        """

        amount = sp.sympify(amount)
        log_scale = sp.sympify(log_scale)
        left = self.multiply(self.add(state, amount), log_scale)
        right = self.add(
            self.multiply(state, log_scale),
            sp.exp(log_scale) * amount,
        )
        return (
            sp.simplify(left.a - right.a),
            sp.simplify(left.v - right.v),
        )

    def power_weight(self, nu: sp.Expr, weight: sp.Expr) -> AMPowerWeight:
        return AMPowerWeight(self.a, self.v, sp.sympify(nu), sp.sympify(weight))

    def shifted_M(self, expr: sp.Expr, shift: sp.Expr) -> sp.Expr:
        """Apply the shifted process operator ``M - shift``."""

        return sp.expand(self.M(expr) - sp.sympify(shift) * sp.sympify(expr))

    def pbw_residual(self, expr: sp.Expr, *, m: int, n: int) -> sp.Expr:
        """Verify the PBW reordering ``M^n A^m = A^m (M-m)^n`` on ``expr``.

        A zero result certifies the identity for the supplied expression.  This
        helper exposes the ordered algebraic consequence of Addition and
        Multiplication; it does not replace the literal construction history.
        """

        if m < 0 or n < 0:
            raise ValueError("m and n must be non-negative")

        left = self.frame.iterate("A", expr, m)
        left = self.frame.iterate("M", left, n)

        right = sp.sympify(expr)
        for _ in range(n):
            right = self.shifted_M(right, m)
        right = self.frame.iterate("A", right, m)
        return sp.simplify(sp.expand(left - right))
