"""Function theory generated by Addition (A) and Multiplication (M).

Here **A means Addition** and **M means Multiplication**.  They are the two
arithmetic process directions of the one-variable AEG construction, not names
for generic operators.

In logarithmic multiplicative coordinate ``v`` the infinitesimal process frame is

    A = d/da,
    M = d/dv + a d/da,

so ``[A,M] = A``.  Their finite flows are ordinary addition and multiplication:

    T_t: (a,v) -> (a+t, v),
    S_s: (a,v) -> (exp(s)*a, v+s),

with

    S_s T_t = T_(exp(s)t) S_s.

The module also exposes the A/M power-weight lattice, its product/lowering laws,
resonant process primitives, PBW reordering, and the ordered A/M path-flow
formula.  These are concrete consequences of Addition and Multiplication; they
sit above Shakespeare's generic history/search machinery and do not exclude
other function theories.
"""

from __future__ import annotations

from dataclasses import dataclass

import sympy as sp

from ..frame import ProcessFrame


def affine_am_frame(a: sp.Symbol, v: sp.Symbol) -> ProcessFrame:
    """Return the canonical Addition/Multiplication process frame."""

    return ProcessFrame(
        assignments=(a, v),
        generators={
            "A": {a: sp.S.One, v: sp.S.Zero},
            "M": {a: a, v: sp.S.One},
        },
    )


@dataclass(frozen=True)
class AMState:
    """State coordinates for the finite Addition/Multiplication action."""

    a: sp.Expr
    v: sp.Expr


@dataclass(frozen=True)
class AMPowerWeight:
    """One point of the Addition/Multiplication power-weight lattice.

    The represented process function is

        Phi_(nu,w) = a**nu * exp((w-nu)*v).

    Its arithmetic process laws are

        M Phi_(nu,w) = w Phi_(nu,w),
        A Phi_(nu,w) = nu Phi_(nu-1,w-1),

    while multiplication adds lattice labels:

        Phi_(nu,w) Phi_(mu,z) = Phi_(nu+mu,w+z).
    """

    a: sp.Symbol
    v: sp.Symbol
    nu: sp.Expr
    weight: sp.Expr

    @property
    def expression(self) -> sp.Expr:
        return self.a ** self.nu * sp.exp((self.weight - self.nu) * self.v)

    def product(self, other: "AMPowerWeight") -> "AMPowerWeight":
        """Objectify multiplication as addition of power/weight labels."""

        if self.a != other.a or self.v != other.v:
            raise ValueError("power-weight elements must use the same A/M coordinates")
        return AMPowerWeight(
            self.a,
            self.v,
            sp.simplify(self.nu + other.nu),
            sp.simplify(self.weight + other.weight),
        )


@dataclass(frozen=True)
class AMPrimitive:
    """One process primitive/integral certificate in the A/M calculus.

    ``resonant`` records when inversion of a process weight fails and a
    logarithmic/Jordan-type extension is required.  ``exceptional_factor`` is
    the factor whose vanishing marks that resonance locus.
    """

    generator: str
    integrand: AMPowerWeight
    expression: sp.Expr
    resonant: bool
    exceptional_factor: sp.Expr


@dataclass(frozen=True)
class AMPathFlow:
    """Ordered flow generated by ``alpha(t) A + beta(t) M``.

    ``history_term`` is the accumulated Addition contribution after later
    Multiplication history has reweighted it.
    """

    start: sp.Expr
    end: sp.Expr
    beta_integral: sp.Expr
    history_term: sp.Expr
    a_end: sp.Expr
    v_end: sp.Expr


@dataclass(frozen=True)
class AMFunctionTheory:
    """Concrete function calculus generated by Addition and Multiplication.

    A/M is one function-theory layer.  Shakespeare's literal histories, task
    quotients, grammar discovery, and presentation search do not depend on it.
    """

    a: sp.Symbol
    v: sp.Symbol

    @property
    def frame(self) -> ProcessFrame:
        return affine_am_frame(self.a, self.v)

    def A(self, expr: sp.Expr) -> sp.Expr:
        """Apply the infinitesimal Addition process."""

        return self.frame.apply("A", expr)

    def M(self, expr: sp.Expr) -> sp.Expr:
        """Apply the infinitesimal Multiplication process."""

        return self.frame.apply("M", expr)

    def commutator(self, expr: sp.Expr) -> sp.Expr:
        """Return ``[A,M] expr``; in this frame it equals ``A(expr)``."""

        return self.frame.commutator("A", "M", expr)

    def add(self, state: AMState, amount: sp.Expr) -> AMState:
        """Finite Addition flow ``T_amount``."""

        amount = sp.sympify(amount)
        return AMState(sp.expand(state.a + amount), sp.sympify(state.v))

    def multiply(self, state: AMState, log_scale: sp.Expr) -> AMState:
        """Finite Multiplication flow ``S_log_scale``."""

        log_scale = sp.sympify(log_scale)
        return AMState(
            sp.expand(sp.exp(log_scale) * state.a),
            sp.expand(state.v + log_scale),
        )

    def finite_relation_residual(
        self,
        state: AMState,
        *,
        amount: sp.Expr,
        log_scale: sp.Expr,
    ) -> tuple[sp.Expr, sp.Expr]:
        """Verify ``S_s T_t = T_(exp(s)t) S_s`` on one symbolic state."""

        amount = sp.sympify(amount)
        log_scale = sp.sympify(log_scale)
        left = self.multiply(self.add(state, amount), log_scale)
        right = self.add(
            self.multiply(state, log_scale),
            sp.exp(log_scale) * amount,
        )
        return (
            sp.simplify(left.a - right.a),
            sp.simplify(left.v - right.v),
        )

    def power_weight(self, nu: sp.Expr, weight: sp.Expr) -> AMPowerWeight:
        return AMPowerWeight(self.a, self.v, sp.sympify(nu), sp.sympify(weight))

    def multiply_power_weights(
        self,
        left: AMPowerWeight,
        right: AMPowerWeight,
    ) -> AMPowerWeight:
        """Multiply two lattice elements while retaining their process labels."""

        return left.product(right)

    def A_primitive(self, element: AMPowerWeight) -> AMPrimitive:
        """Invert the Addition process on one power-weight element.

        Away from ``nu = -1`` the primitive is another lattice element.  At
        ``nu = -1`` the lattice step is singular and the required extension is
        logarithmic in the additive assignment ``a``.
        """

        if element.a != self.a or element.v != self.v:
            raise ValueError("power-weight element belongs to another A/M frame")
        exceptional = sp.simplify(element.nu + 1)
        if exceptional == 0:
            primitive = sp.exp((element.weight + 1) * self.v) * sp.log(self.a)
            return AMPrimitive(
                generator="A",
                integrand=element,
                expression=primitive,
                resonant=True,
                exceptional_factor=exceptional,
            )

        next_element = self.power_weight(element.nu + 1, element.weight + 1)
        return AMPrimitive(
            generator="A",
            integrand=element,
            expression=sp.simplify(next_element.expression / exceptional),
            resonant=False,
            exceptional_factor=exceptional,
        )

    def M_primitive(self, element: AMPowerWeight) -> AMPrimitive:
        """Invert the Multiplication process on one power-weight element.

        Away from ``weight = 0`` this divides by the multiplicative process
        weight.  At zero weight, the function is invariant under ``M`` and the
        primitive acquires a linear ``v`` extension, the multiplicative analogue
        of a Jordan/resonance step.
        """

        if element.a != self.a or element.v != self.v:
            raise ValueError("power-weight element belongs to another A/M frame")
        exceptional = sp.simplify(element.weight)
        if exceptional == 0:
            return AMPrimitive(
                generator="M",
                integrand=element,
                expression=sp.expand(self.v * element.expression),
                resonant=True,
                exceptional_factor=exceptional,
            )

        return AMPrimitive(
            generator="M",
            integrand=element,
            expression=sp.simplify(element.expression / exceptional),
            resonant=False,
            exceptional_factor=exceptional,
        )

    def primitive_residual(self, primitive: AMPrimitive) -> sp.Expr:
        """Return the exact process-primitive certificate residual."""

        if primitive.generator == "A":
            image = self.A(primitive.expression)
        elif primitive.generator == "M":
            image = self.M(primitive.expression)
        else:
            raise ValueError(f"unknown A/M primitive generator: {primitive.generator!r}")
        return sp.simplify(sp.expand(image - primitive.integrand.expression))

    def shifted_M(self, expr: sp.Expr, shift: sp.Expr) -> sp.Expr:
        """Apply the shifted process operator ``M - shift``."""

        return sp.expand(self.M(expr) - sp.sympify(shift) * sp.sympify(expr))

    def pbw_residual(self, expr: sp.Expr, *, m: int, n: int) -> sp.Expr:
        """Verify ``M^n A^m = A^m (M-m)^n`` on ``expr``."""

        if m < 0 or n < 0:
            raise ValueError("m and n must be non-negative")

        left = self.frame.iterate("A", expr, m)
        left = self.frame.iterate("M", left, n)

        right = sp.sympify(expr)
        for _ in range(n):
            right = self.shifted_M(right, m)
        right = self.frame.iterate("A", right, m)
        return sp.simplify(sp.expand(left - right))

    def path_flow(
        self,
        alpha: sp.Expr,
        beta: sp.Expr,
        time: sp.Symbol,
        *,
        start: sp.Expr,
        end: sp.Expr,
        a0: sp.Expr,
        v0: sp.Expr,
    ) -> AMPathFlow:
        """Integrate the ordered process ``alpha A + beta M`` symbolically.

        For

            da/dt = alpha(t) + beta(t) a,
            dv/dt = beta(t),

        the result keeps the history-weighting term explicit:

            a(T) = exp(B(T)) a0
                   + integral exp(B(T)-B(t)) alpha(t) dt.

        Later Multiplication process therefore reweights earlier Addition
        history.  SymPy performs the integral backend; the returned decomposition
        preserves its process interpretation.
        """

        alpha = sp.sympify(alpha)
        beta = sp.sympify(beta)
        start = sp.sympify(start)
        end = sp.sympify(end)
        a0 = sp.sympify(a0)
        v0 = sp.sympify(v0)

        tau = sp.Dummy("tau")
        sigma = sp.Dummy("sigma")
        beta_sigma = beta.subs(time, sigma)
        beta_integral = sp.integrate(beta_sigma, (sigma, start, end))
        beta_to_tau = sp.integrate(beta_sigma, (sigma, start, tau))
        alpha_tau = alpha.subs(time, tau)
        history_term = sp.integrate(
            sp.exp(beta_integral - beta_to_tau) * alpha_tau,
            (tau, start, end),
        )
        a_end = sp.simplify(sp.exp(beta_integral) * a0 + history_term)
        v_end = sp.simplify(v0 + beta_integral)
        return AMPathFlow(
            start=start,
            end=end,
            beta_integral=sp.simplify(beta_integral),
            history_term=sp.simplify(history_term),
            a_end=a_end,
            v_end=v_end,
        )
