"""Restricted Riccati: canonicalize -> transport -> genuine completion.

Question
--------
Can the first canonical-observer vertical slice distinguish motion inside a
restricted affine observer family from a process direction that genuinely forces
the representation to enlarge?

Primitive data
--------------
Start with the Riccati process

    dx/dt = a + b x + c x^2.

The process frame contains the three named directions

    A = d/dx,
    M = x d/dx,
    Q = x^2 d/dx.

But the *observer family* is deliberately restricted to affine changes of
variable.  Its local parameters are the lower instantaneous root ``r`` and the
root separation ``d``.  They are selected by the exact canonicalization
conditions that both ``r`` and ``r+d`` are roots of the instantaneous Riccati
polynomial.

No PSL(2) / Möbius observer is supplied, and ``Q`` is not declared removable.

Shakespeare reconstruction
---------------------------
``ProcessDirection`` records the physical generator as a combination of the
process frame before any assignment ODE is privileged.  ``Canonicalization``
then differentiates the two root constraints along arbitrary local coefficient
rates ``a_dot,b_dot,c_dot``.  The resulting ``ObserverConnection`` is therefore
the differential consequence of preserving the affine canonical form; the
observer rates are not hand-written dynamics.

In the affine observer coordinate

    y = (x-r)/d,

the transformed process is

    dy/dt = -r_dot/d
            + (-kappa-d_dot/d) y
            + kappa y^2,

with ``kappa=c*d``.  The first two terms lie in the affine observer algebra
``<A,M>``.  The quadratic ``Q`` direction remains with nonzero coefficient
``kappa`` and cannot be generated by affine observer motion.

``CanonicalDecomposition`` records this exact split with an explicit residual
certificate.  Adding the completion direction gives

    [A,M] = A,
    [A,Q] = 2 M,
    [M,Q] = Q,

so the minimal Lie closure is the standard three-dimensional sl(2) realization.

Calibration statement
---------------------
Passing this file certifies that:

1. ``ProcessDirection`` lowers the Riccati process to the ordinary assignment ODE
   without making that ODE the process ontology;
2. exact root canonicalization uniquely induces local affine observer rates;
3. those rates keep both canonicalization constraints differentiated to zero;
4. in the moving affine observer, connection terms occupy only ``A`` and ``M``;
5. the ``Q`` coefficient survives as a genuine completion direction; and
6. adjoining ``Q`` closes with ``A,M`` as the sl(2) bracket table above.

Boundary
--------
This is not yet a general Riccati solver, a PSL(2) observer API, a theorem about
all canonicalization strata, or a public representation-completion engine.
The completion partition is stated by this calibration and certified exactly;
later independent tests must determine which decomposition information deserves
a reusable discovery backend.
"""

import sympy as sp

from aeg_shakespeare.analysis.decomposition import CanonicalDecomposition
from aeg_shakespeare.presentation.canonicalization import Canonicalization
from aeg_shakespeare.process.local.direction import ProcessDirection
from aeg_shakespeare.process.local.frame import ProcessFrame


def riccati_frame(x):
    return ProcessFrame(
        assignments=(x,),
        generators={
            "A": {x: sp.S.One},
            "M": {x: x},
            "Q": {x: x**2},
        },
    )


def test_process_direction_precedes_assignment_ode():
    x = sp.Symbol("x")
    a, b, c = sp.symbols("a b c")
    frame = riccati_frame(x)
    direction = ProcessDirection(
        frame,
        {"A": a, "M": b, "Q": c},
        label="Riccati process",
    )

    expected = sp.expand(a + b * x + c * x**2)
    assert direction.apply(x) == expected
    system = direction.as_system(name="D_t")
    assert system.rules[x] == expected


def test_affine_root_canonicalization_induces_observer_connection():
    a, b, c = sp.symbols("a b c")
    r, d = sp.symbols("r d", nonzero=True)
    a_dot, b_dot, c_dot = sp.symbols("a_dot b_dot c_dot")

    canonicalization = Canonicalization(
        observer_parameters=(r, d),
        constraints=(
            a + b * r + c * r**2,
            a + b * (r + d) + c * (r + d) ** 2,
        ),
        label="affine Riccati roots",
    )
    connection = canonicalization.induced_connection(
        {a: a_dot, b: b_dot, c: c_dot}
    )

    assert connection.certified
    expected_r_dot = sp.simplify(
        -(a_dot + b_dot * r + c_dot * r**2) / (b + 2 * c * r)
    )
    assert sp.simplify(connection.rate(r) - expected_r_dot) == 0

    # Frozen Riccati coefficients give a frozen affine canonical observer.
    frozen = canonicalization.induced_connection(
        {a: sp.S.Zero, b: sp.S.Zero, c: sp.S.Zero}
    )
    assert frozen.certified
    assert sp.simplify(frozen.rate(r)) == 0
    assert sp.simplify(frozen.rate(d)) == 0


def test_restricted_affine_observer_leaves_q_as_completion_direction():
    x, y = sp.symbols("x y")
    a, b, c = sp.symbols("a b c")
    r, d = sp.symbols("r d", nonzero=True)
    a_dot, b_dot, c_dot = sp.symbols("a_dot b_dot c_dot")

    physical = ProcessDirection(
        riccati_frame(x),
        {"A": a, "M": b, "Q": c},
    )
    canonicalization = Canonicalization(
        observer_parameters=(r, d),
        constraints=(
            a + b * r + c * r**2,
            a + b * (r + d) + c * (r + d) ** 2,
        ),
    )
    connection = canonicalization.induced_connection(
        {a: a_dot, b: b_dot, c: c_dot}
    )

    # On the canonical leaf the Riccati polynomial is
    # c (x-r) (x-r-d).  Substitute x=r+d*y only after the observer has been
    # selected; the affine chart is a representation shadow, not primitive data.
    canonical_leaf = {
        a: c * r * (r + d),
        b: -c * (2 * r + d),
    }
    r_dot = sp.simplify(connection.rate(r).subs(canonical_leaf))
    d_dot = sp.simplify(connection.rate(d).subs(canonical_leaf))
    kappa = sp.expand(c * d)

    x_dot = sp.expand(
        physical.apply(x).subs(x, r + d * y).subs(canonical_leaf)
    )
    y_dot = sp.simplify((x_dot - r_dot - y * d_dot) / d)
    expected_y_dot = sp.expand(
        -r_dot / d
        + (-kappa - d_dot / d) * y
        + kappa * y**2
    )
    assert sp.simplify(y_dot - expected_y_dot) == 0

    observed_frame = riccati_frame(y)
    observed = ProcessDirection(
        observed_frame,
        {
            "A": -r_dot / d,
            "M": -kappa - d_dot / d,
            "Q": kappa,
        },
        label="moving affine Riccati presentation",
    )
    assert sp.simplify(observed.apply(y) - y_dot) == 0

    renormalizable = ProcessDirection(
        observed_frame,
        {
            "A": -r_dot / d,
            "M": -kappa - d_dot / d,
        },
        label="affine observer tangent",
    )
    resonant = ProcessDirection(observed_frame, {}, label="no Riccati resonance")
    completion = ProcessDirection(
        observed_frame,
        {"Q": kappa},
        label="quadratic completion residual",
    )
    residual = sp.simplify(
        observed.apply(y)
        - renormalizable.apply(y)
        - resonant.apply(y)
        - completion.apply(y)
    )
    decomposition = CanonicalDecomposition(
        source=observed,
        renormalizable=renormalizable,
        resonant=resonant,
        completion=completion,
        certificate=residual,
        label="restricted affine Riccati split",
    )

    assert decomposition.certificate == 0
    assert sp.simplify(decomposition.completion.coefficient("Q") - kappa) == 0
    assert decomposition.completion.coefficient("A") == 0
    assert decomposition.completion.coefficient("M") == 0

    # Minimal Lie-completion certificate: A,M,Q close as sl(2).
    assert sp.expand(observed_frame.commutator("A", "M", y) - 1) == 0
    assert sp.expand(observed_frame.commutator("A", "Q", y) - 2 * y) == 0
    assert sp.expand(observed_frame.commutator("M", "Q", y) - y**2) == 0
