"""Magnetic translations: visible addition with a hidden flux-dependent central residual.

Question
--------
Galilean mechanics exposed a nonzero central generator residual that disappears
at the level of visible phase-space maps.  Does an independent physical system
produce the same structural pressure, and can the resulting finite residual now
be carried by the same minimal ``ProcessCocycle`` abstraction?

Primitive data
--------------
Use planar translations with parameters ``a=(a_x,a_y)`` and ordinary visible
composition

    a * b = a + b.

Place a charged particle in a uniform perpendicular magnetic field.  We use a
fixed symmetric-gauge convention and write ``beta = q B``.  At the finite lifted
level the translation also carries a phase/history coordinate.  At the
Hamiltonian level the magnetic-translation generators are

    K_x = p_x - beta y / 2,
    K_y = p_y + beta x / 2.

No magnetic-translation-group class, projective representation, cohomology
machinery, or spectral theory is supplied.

Classical lineage
-----------------
Magnetic translations in a uniform field were developed independently by Brown
and Zak.  See [Brown-1964] and [Zak-1964].  The sign of the phase depends on
charge, gauge, operator-order, and active/passive conventions; this vignette
fixes one convention and tests only convention-invariant structural content:
ordinary visible translation composition acquires a central area/flux residual
in a lifted realization.

Shakespeare reconstruction
---------------------------
``ProcessFamily`` sees the visible translation law ``a+b``.  The calibrated
lifted realization changes a phase/history coordinate by

    (beta / (2 hbar)) (a_x y - a_y x).

The corresponding finite central residual is represented by ``ProcessCocycle``:

    omega(a,b) = beta/(2 hbar) * (a wedge b).

The generic cocycle verifier checks

    omega(a,b) + omega(a+b,c)
      = omega(b,c) + omega(a,b+c).

The generic central-commutator helper then returns

    omega(a,b) - omega(b,a)
      = beta/hbar * (a wedge b),

while the visible endpoint is unchanged.  The explicit lifted-state
calculation independently certifies that the API residual equals the actual
phase/history discrepancy of this realization.

At the Hamiltonian layer the same pressure appears infinitesimally:

    {K_x, K_y} = - beta.

The right-hand side is nonzero but constant, hence its Hamiltonian vector field
vanishes.  Consequently the finite canonical flows generated by ``K_x`` and
``K_y`` commute as visible phase-space maps even though their generator
presentation retains a central residual.

Calibration statement
---------------------
Passing this file certifies that:

1. ``ProcessFamily`` correctly represents ordinary visible planar translation;
2. ``ProcessCocycle`` represents the exact area-dependent lifted residual and
   certifies its 2-cocycle law;
3. the generic central-commutator residual equals the explicit flux-dependent
   phase difference between the two translation orders;
4. the magnetic-translation generators commute with the uniform-field
   Hamiltonian and satisfy ``{K_x,K_y}=-beta``;
5. the central bracket has zero visible Hamiltonian vector field, so visible
   canonical translation flows commute.

New reusable abstraction
-------------------------
This example now shares the minimal ``ProcessCocycle`` abstraction with the
independent Galilean mass calibration.  The physical realization and cocycle
formula remain problem-specific.

Boundary
--------
This is not a construction of the full magnetic translation group, a theorem
about all gauges, or a quantum representation theory.  ``ProcessCocycle`` stores
one additive finite composition residual; it does not quotient cocycles by
coboundaries or turn the package into a cohomology engine.

References
----------
[Brown-1964] E. Brown, "Bloch Electrons in a Uniform Magnetic Field",
*Physical Review* 133, A1038 (1964), DOI: 10.1103/PhysRev.133.A1038.

[Zak-1964] J. Zak, "Magnetic Translation Group", *Physical Review* 134,
A1602-A1606 (1964), DOI: 10.1103/PhysRev.134.A1602.
"""

import sympy as sp

from process_geometry.process.finite import (
    ProcessCocycle,
    ProcessFamily,
    central_commutator_residual,
    verify_process_cocycle,
)


def _pair_add(left, right):
    return (
        sp.expand(left[0] + right[0]),
        sp.expand(left[1] + right[1]),
    )


def _wedge(left, right):
    return sp.expand(left[0] * right[1] - left[1] * right[0])


def _lifted_translation(parameter, state, *, beta, hbar):
    """One fixed-convention lift of a planar translation.

    ``state=(x,y,theta)`` and ``theta`` is an additive phase exponent.  The
    visible projection forgets ``theta``.
    """

    ax, ay = parameter
    x, y, theta = state
    return (
        sp.expand(x + ax),
        sp.expand(y + ay),
        sp.expand(theta + beta * (ax * y - ay * x) / (2 * hbar)),
    )


def _poisson(f, g, x, y, px, py):
    return sp.expand(
        sp.diff(f, x) * sp.diff(g, px)
        - sp.diff(f, px) * sp.diff(g, x)
        + sp.diff(f, y) * sp.diff(g, py)
        - sp.diff(f, py) * sp.diff(g, y)
    )


def _hamiltonian_vector_field(f, x, y, px, py):
    return (
        sp.expand(sp.diff(f, px)),
        sp.expand(sp.diff(f, py)),
        sp.expand(-sp.diff(f, x)),
        sp.expand(-sp.diff(f, y)),
    )


def test_magnetic_translation_has_flux_cocycle_but_ordinary_visible_composition():
    ax, ay, bx, by, cx, cy = sp.symbols("a_x a_y b_x b_y c_x c_y", real=True)
    x, y, theta = sp.symbols("x y theta", real=True)
    beta, hbar = sp.symbols("beta hbar", nonzero=True, real=True)

    a = (ax, ay)
    b = (bx, by)
    c = (cx, cy)
    translations = ProcessFamily(
        "T2",
        _pair_add,
        identity=(sp.S.Zero, sp.S.Zero),
    )

    assert translations.parameters_equivalent(
        translations.compose_parameters(a, b),
        (ax + bx, ay + by),
    )

    cocycle = ProcessCocycle(
        translations,
        lambda left, right: sp.expand(
            beta * _wedge(left, right) / (2 * hbar)
        ),
        label="magnetic flux phase",
    )
    assert verify_process_cocycle(
        cocycle,
        ((a, b, c),),
        normalization_parameters=(a,),
    ).exact

    state = (x, y, theta)
    after_b_then_a = _lifted_translation(
        a,
        _lifted_translation(b, state, beta=beta, hbar=hbar),
        beta=beta,
        hbar=hbar,
    )
    direct_ab = _lifted_translation(
        translations.compose_parameters(a, b),
        state,
        beta=beta,
        hbar=hbar,
    )

    assert sp.simplify(after_b_then_a[0] - direct_ab[0]) == 0
    assert sp.simplify(after_b_then_a[1] - direct_ab[1]) == 0
    assert sp.simplify(
        after_b_then_a[2] - direct_ab[2] - cocycle.value(a, b)
    ) == 0

    after_a_then_b = _lifted_translation(
        b,
        _lifted_translation(a, state, beta=beta, hbar=hbar),
        beta=beta,
        hbar=hbar,
    )
    assert sp.simplify(after_b_then_a[0] - after_a_then_b[0]) == 0
    assert sp.simplify(after_b_then_a[1] - after_a_then_b[1]) == 0

    commutator = central_commutator_residual(cocycle, a, b)
    expected_commutator_phase = sp.expand(beta * _wedge(a, b) / hbar)
    assert sp.simplify(commutator - expected_commutator_phase) == 0
    assert sp.simplify(
        after_b_then_a[2] - after_a_then_b[2] - commutator
    ) == 0


def test_magnetic_translation_generators_retain_central_bracket_invisible_to_flows():
    x, y, px, py = sp.symbols("x y p_x p_y", real=True)
    beta = sp.symbols("beta", nonzero=True, real=True)
    mass = sp.symbols("m", positive=True)
    a, b = sp.symbols("a b", real=True)

    pi_x = px + beta * y / 2
    pi_y = py - beta * x / 2
    H = sp.expand((pi_x**2 + pi_y**2) / (2 * mass))
    Kx = sp.expand(px - beta * y / 2)
    Ky = sp.expand(py + beta * x / 2)

    assert sp.simplify(_poisson(Kx, H, x, y, px, py)) == 0
    assert sp.simplify(_poisson(Ky, H, x, y, px, py)) == 0

    central = sp.expand(_poisson(Kx, Ky, x, y, px, py))
    assert sp.simplify(central + beta) == 0
    assert _hamiltonian_vector_field(central, x, y, px, py) == (
        sp.S.Zero,
        sp.S.Zero,
        sp.S.Zero,
        sp.S.Zero,
    )

    def flow_kx(parameter, state):
        sx, sy, spx, spy = state
        return (
            sp.expand(sx + parameter),
            sy,
            spx,
            sp.expand(spy + beta * parameter / 2),
        )

    def flow_ky(parameter, state):
        sx, sy, spx, spy = state
        return (
            sx,
            sp.expand(sy + parameter),
            sp.expand(spx - beta * parameter / 2),
            spy,
        )

    state = (x, y, px, py)
    xy = flow_kx(a, flow_ky(b, state))
    yx = flow_ky(b, flow_kx(a, state))
    assert all(sp.simplify(left - right) == 0 for left, right in zip(xy, yx))
