"""Magnetic translations: visible addition with a hidden flux-dependent central residual.

Question
--------
Galilean mechanics exposed a nonzero central generator residual that disappears
at the level of visible phase-space maps.  Does an independent physical system
produce the same structural pressure on the frozen finite-family API?

Primitive data
--------------
Use planar translations with parameters ``a=(a_x,a_y)`` and ordinary visible
composition

    a * b = a + b.

Place a charged particle in a uniform perpendicular magnetic field.  We use a
fixed symmetric-gauge convention and write ``beta = q B``.  At the finite lifted
level the translation also carries a phase/history coordinate.  At the
Hamiltonian level the magnetic-translation generators are

    K_x = p_x - beta y / 2,
    K_y = p_y + beta x / 2.

No magnetic-translation-group class, cocycle API, projective representation,
cohomology machinery, or spectral theory is supplied.

Classical lineage
-----------------
Magnetic translations in a uniform field were developed independently by Brown
and Zak.  See [Brown-1964] and [Zak-1964].  The sign of the phase depends on
charge, gauge, operator-order, and active/passive conventions; this vignette
fixes one convention and tests only convention-invariant structural content:
ordinary visible translation composition acquires a central area/flux residual
in a lifted realization.

Shakespeare reconstruction
---------------------------
``ProcessFamily`` still sees the visible translation law ``a+b``.  We then build
a separate lifted realization whose phase coordinate changes by

    (beta / (2 hbar)) (a_x y - a_y x).

Composing lifted translations in the two orders yields the same visible point
but different central phase histories.  Relative to the direct ``a+b`` step,

    omega(a,b) = beta/(2 hbar) * (a wedge b)

is the additive phase residual, and it obeys the exact 2-cocycle identity

    omega(a,b) + omega(a+b,c)
      = omega(b,c) + omega(a,b+c).

The commutator residual is

    omega(a,b) - omega(b,a)
      = beta/hbar * (a wedge b),

which is proportional to the magnetic flux through the oriented parallelogram.

At the Hamiltonian layer the same pressure appears infinitesimally:

    {K_x, K_y} = - beta.

The right-hand side is nonzero but constant, hence its Hamiltonian vector field
vanishes.  Consequently the finite canonical flows generated by ``K_x`` and
``K_y`` commute as visible phase-space maps even though their generator
presentation retains a central residual.

Calibration statement
---------------------
Passing this file certifies that:

1. the frozen ``ProcessFamily`` API correctly represents ordinary visible planar
   translation composition;
2. an independent lifted magnetic realization has an exact area-dependent
   central composition residual satisfying the 2-cocycle identity;
3. the two translation orders have identical visible state but differ by the
   expected central flux phase;
4. the magnetic-translation generators commute with the uniform-field
   Hamiltonian and satisfy ``{K_x,K_y}=-beta``;
5. the central bracket has zero visible Hamiltonian vector field, so visible
   canonical translation flows commute.

New reusable abstraction
-------------------------
None in this PR.  This is the first independent organism after the Galilean
example to reproduce the same ``visible law + hidden central residual`` pressure.

Unresolved manual choice
------------------------
The evidence now strongly suggests a small finite central-residual/cocycle
abstraction, but this test deliberately leaves its exact API shape undecided.
In particular, the Galilean residual has so far been exposed most naturally at
the generator/affine-response level, while magnetic translations expose an
explicit finite 2-cocycle.  The common interface should be designed from both,
not inferred from the magnetic example alone.

Boundary
--------
This is not a construction of the full magnetic translation group, a theorem
about all gauges, or a quantum representation theory.  The lifted phase model is
a calibrated symbolic realization used to expose composition residuals.

References
----------
[Brown-1964] E. Brown, "Bloch Electrons in a Uniform Magnetic Field",
*Physical Review* 133, A1038 (1964), DOI: 10.1103/PhysRev.133.A1038.

[Zak-1964] J. Zak, "Magnetic Translation Group", *Physical Review* 134,
A1602-A1606 (1964), DOI: 10.1103/PhysRev.134.A1602.
"""

import sympy as sp

from aeg_shakespeare import ProcessFamily


def _pair_add(left, right):
    return (
        sp.expand(left[0] + right[0]),
        sp.expand(left[1] + right[1]),
    )


def _wedge(left, right):
    return sp.expand(left[0] * right[1] - left[1] * right[0])


def _lifted_translation(parameter, state, *, beta, hbar):
    """One fixed-convention lift of a planar translation.

    ``state=(x,y,theta)`` and ``theta`` is an additive phase exponent.  The
    visible projection forgets ``theta``.
    """

    ax, ay = parameter
    x, y, theta = state
    return (
        sp.expand(x + ax),
        sp.expand(y + ay),
        sp.expand(theta + beta * (ax * y - ay * x) / (2 * hbar)),
    )


def _poisson(f, g, x, y, px, py):
    return sp.expand(
        sp.diff(f, x) * sp.diff(g, px)
        - sp.diff(f, px) * sp.diff(g, x)
        + sp.diff(f, y) * sp.diff(g, py)
        - sp.diff(f, py) * sp.diff(g, y)
    )


def _hamiltonian_vector_field(f, x, y, px, py):
    return (
        sp.expand(sp.diff(f, px)),
        sp.expand(sp.diff(f, py)),
        sp.expand(-sp.diff(f, x)),
        sp.expand(-sp.diff(f, y)),
    )


def test_magnetic_translation_has_flux_cocycle_but_ordinary_visible_composition():
    ax, ay, bx, by, cx, cy = sp.symbols("a_x a_y b_x b_y c_x c_y", real=True)
    x, y, theta = sp.symbols("x y theta", real=True)
    beta, hbar = sp.symbols("beta hbar", nonzero=True, real=True)

    a = (ax, ay)
    b = (bx, by)
    c = (cx, cy)
    translations = ProcessFamily(
        "T2",
        _pair_add,
        identity=(sp.S.Zero, sp.S.Zero),
    )

    # The frozen family API sees only ordinary planar translation.
    assert translations.parameters_equivalent(
        translations.compose_parameters(a, b),
        (ax + bx, ay + by),
    )

    state = (x, y, theta)
    after_b_then_a = _lifted_translation(
        a,
        _lifted_translation(b, state, beta=beta, hbar=hbar),
        beta=beta,
        hbar=hbar,
    )
    direct_ab = _lifted_translation(
        translations.compose_parameters(a, b),
        state,
        beta=beta,
        hbar=hbar,
    )

    # Visible position agrees; only the lifted phase/history remembers order.
    assert sp.simplify(after_b_then_a[0] - direct_ab[0]) == 0
    assert sp.simplify(after_b_then_a[1] - direct_ab[1]) == 0

    omega_ab = sp.expand(beta * _wedge(a, b) / (2 * hbar))
    assert sp.simplify(after_b_then_a[2] - direct_ab[2] - omega_ab) == 0

    # The additive central residual is an exact 2-cocycle.
    omega = lambda left, right: sp.expand(
        beta * _wedge(left, right) / (2 * hbar)
    )
    cocycle_residual = sp.expand(
        omega(a, b)
        + omega(_pair_add(a, b), c)
        - omega(b, c)
        - omega(a, _pair_add(b, c))
    )
    assert sp.simplify(cocycle_residual) == 0

    after_a_then_b = _lifted_translation(
        b,
        _lifted_translation(a, state, beta=beta, hbar=hbar),
        beta=beta,
        hbar=hbar,
    )
    assert sp.simplify(after_b_then_a[0] - after_a_then_b[0]) == 0
    assert sp.simplify(after_b_then_a[1] - after_a_then_b[1]) == 0
    expected_commutator_phase = sp.expand(beta * _wedge(a, b) / hbar)
    assert sp.simplify(
        after_b_then_a[2] - after_a_then_b[2] - expected_commutator_phase
    ) == 0


def test_magnetic_translation_generators_retain_central_bracket_invisible_to_flows():
    x, y, px, py = sp.symbols("x y p_x p_y", real=True)
    beta = sp.symbols("beta", nonzero=True, real=True)
    mass = sp.symbols("m", positive=True)
    a, b = sp.symbols("a b", real=True)

    # Symmetric-gauge realization.  Mechanical momenta enter H, while K_x,K_y
    # generate magnetic translations.
    pi_x = px + beta * y / 2
    pi_y = py - beta * x / 2
    H = sp.expand((pi_x**2 + pi_y**2) / (2 * mass))
    Kx = sp.expand(px - beta * y / 2)
    Ky = sp.expand(py + beta * x / 2)

    assert sp.simplify(_poisson(Kx, H, x, y, px, py)) == 0
    assert sp.simplify(_poisson(Ky, H, x, y, px, py)) == 0

    central = sp.expand(_poisson(Kx, Ky, x, y, px, py))
    assert sp.simplify(central + beta) == 0
    assert _hamiltonian_vector_field(central, x, y, px, py) == (
        sp.S.Zero,
        sp.S.Zero,
        sp.S.Zero,
        sp.S.Zero,
    )

    # Explicit finite canonical flows commute visibly even though the generators
    # retain the nonzero central bracket.
    def flow_kx(parameter, state):
        sx, sy, spx, spy = state
        return (
            sp.expand(sx + parameter),
            sy,
            spx,
            sp.expand(spy + beta * parameter / 2),
        )

    def flow_ky(parameter, state):
        sx, sy, spx, spy = state
        return (
            sx,
            sp.expand(sy + parameter),
            sp.expand(spx - beta * parameter / 2),
            spy,
        )

    state = (x, y, px, py)
    xy = flow_kx(a, flow_ky(b, state))
    yx = flow_ky(b, flow_kx(a, state))
    assert all(sp.simplify(left - right) == 0 for left, right in zip(xy, yx))
