"""Restricted Riccati: canonicalize -> transport -> genuine completion.

Question
--------
Can the first canonical-observer vertical slice distinguish motion inside a
restricted affine observer family from a process direction that genuinely forces
the representation to enlarge?

Primitive data
--------------
Start with the Riccati process

    dx/dt = a + b x + c x^2.

The process frame contains the three named directions

    A = d/dx,
    M = x d/dx,
    Q = x^2 d/dx.

But the *observer family* is deliberately restricted to affine changes of
variable.  Its local parameters are the lower instantaneous root ``r`` and the
root separation ``d``.  They are selected by the exact canonicalization
conditions that both ``r`` and ``r+d`` are roots of the instantaneous Riccati
polynomial.

No PSL(2) / Möbius observer, superposition formula, matrix representation, or
completed ``sl(2)`` algebra is supplied to the canonicalization step.

Classical lineage
-----------------
The time-dependent Riccati equation is a standard Lie-system example: the vector
fields ``d/dx``, ``x d/dx``, and ``x^2 d/dx`` close as a three-dimensional Lie
algebra isomorphic to ``sl(2,R)``; the group-theoretic relation to ``SL(2,R)`` and
nonlinear superposition is classical [Carinena-Marmo-Nasarre-1998].  Standard
matrix-Lie-group and Lie-algebra background is given in [Hall-2015].

This test does **not** use that classical ``sl(2)`` identification as the input
representation.  It intentionally starts from the smaller affine observer
language ``<A,M>`` and asks whether the quadratic direction is forced as a
completion residual.

Shakespeare reconstruction
---------------------------
``ProcessDirection`` records the physical generator as a combination of the
process frame before any assignment ODE is privileged.
``ConstraintCanonicalization`` then differentiates the two root constraints
along arbitrary local coefficient rates ``a_dot,b_dot,c_dot``.  The resulting
``ObserverConnection`` is therefore the differential consequence of preserving
the affine canonical form; the observer rates are not hand-written dynamics.

In the affine observer coordinate

    y = (x-r)/d,

the transformed process is

    dy/dt = -r_dot/d
            + (-kappa-d_dot/d) y
            + kappa y^2,

with ``kappa=c*d``.  The first two terms lie in the affine observer algebra
``<A,M>``.  The quadratic ``Q`` direction remains with nonzero coefficient
``kappa`` and cannot be generated by affine observer motion.

``CanonicalDecomposition`` records this exact split with an explicit residual
certificate.  Only after that split does the test check the familiar bracket
closure

    [A,M] = A,
    [A,Q] = 2 M,
    [M,Q] = Q,

identifying the completed three-dimensional algebra with the standard Riccati
``sl(2)`` shadow.

Calibration statement
---------------------
Passing this file certifies that:

1. ``ProcessDirection`` lowers the Riccati process to the ordinary assignment ODE
   without making that ODE the process ontology;
2. exact root canonicalization uniquely induces local affine observer rates;
3. those rates keep both canonicalization constraints differentiated to zero;
4. in the moving affine observer, connection terms occupy only ``A`` and ``M``;
5. the ``Q`` coefficient survives as a genuine completion direction; and
6. adjoining ``Q`` closes with ``A,M`` as the classical ``sl(2)`` bracket table.

Proof map
---------
1. ``test_process_direction_precedes_assignment_ode`` checks the process-frame
   combination and its assignment-system shadow.
2. ``test_affine_root_canonicalization_induces_observer_connection``
   differentiates both root constraints, checks the exact induced ``r`` rate,
   and verifies zero connection residuals; the frozen-coefficient case is a
   negative control.
3. ``test_restricted_affine_observer_leaves_q_as_completion_direction`` pulls
   the process into the moving affine coordinate, reconstructs the three
   decomposition sectors, checks exact zero decomposition residual, and only
   then verifies the ``A,M,Q`` bracket closure.

Boundary
--------
This is not a general Riccati solver, a PSL(2) observer API, a proof of global
normal-form existence across discriminant strata, or a public automatic
representation-completion engine.  The affine root choice is one exact local
canonicalization in the nondegenerate two-root sector.  The classification of
``Q`` as completion is a statement relative to that restricted observer family.
The Shakespeare interpretation -- canonicalization first, classical ``sl(2)``
identification last -- is the project's reconstruction, not a claim attributed
to the classical references.

References
----------
[Carinena-Marmo-Nasarre-1998] J. F. Carinena, G. Marmo, J. Nasarre,
"The nonlinear superposition principle and the Wei-Norman method,"
arXiv:physics/9802041 (1998), especially the Riccati / ``SL(2,R)`` discussion,
https://arxiv.org/abs/physics/9802041 .

[Hall-2015] Brian C. Hall, *Lie Groups, Lie Algebras, and Representations: An
Elementary Introduction*, 2nd ed., Graduate Texts in Mathematics 222, Springer,
2015, Chapters 2--3; DOI 10.1007/978-3-319-13467-3.
"""

import sympy as sp

from process_geometry.experimental import (
    CanonicalDecomposition,
    ConstraintCanonicalization,
)
from aeg_shakespeare.process.local import ProcessDirection, ProcessFrame


def riccati_frame(x):
    return ProcessFrame(
        assignments=(x,),
        generators={
            "A": {x: sp.S.One},
            "M": {x: x},
            "Q": {x: x**2},
        },
    )


def test_process_direction_precedes_assignment_ode():
    x = sp.Symbol("x")
    a, b, c = sp.symbols("a b c")
    frame = riccati_frame(x)
    direction = ProcessDirection(
        frame,
        {"A": a, "M": b, "Q": c},
        label="Riccati process",
    )

    expected = sp.expand(a + b * x + c * x**2)
    assert direction.apply(x) == expected
    system = direction.as_system(name="D_t")
    assert system.rules[x] == expected


def test_affine_root_canonicalization_induces_observer_connection():
    a, b, c = sp.symbols("a b c")
    r, d = sp.symbols("r d", nonzero=True)
    a_dot, b_dot, c_dot = sp.symbols("a_dot b_dot c_dot")

    canonicalization = ConstraintCanonicalization(
        observer_parameters=(r, d),
        constraints=(
            a + b * r + c * r**2,
            a + b * (r + d) + c * (r + d) ** 2,
        ),
        label="affine Riccati roots",
    )
    connection = canonicalization.induced_connection(
        {a: a_dot, b: b_dot, c: c_dot}
    )

    assert connection.certified
    expected_r_dot = sp.simplify(
        -(a_dot + b_dot * r + c_dot * r**2) / (b + 2 * c * r)
    )
    assert sp.simplify(connection.rate(r) - expected_r_dot) == 0

    # Frozen Riccati coefficients give a frozen affine canonical observer.
    frozen = canonicalization.induced_connection(
        {a: sp.S.Zero, b: sp.S.Zero, c: sp.S.Zero}
    )
    assert frozen.certified
    assert sp.simplify(frozen.rate(r)) == 0
    assert sp.simplify(frozen.rate(d)) == 0


def test_restricted_affine_observer_leaves_q_as_completion_direction():
    x, y = sp.symbols("x y")
    a, b, c = sp.symbols("a b c")
    r, d = sp.symbols("r d", nonzero=True)
    a_dot, b_dot, c_dot = sp.symbols("a_dot b_dot c_dot")

    physical = ProcessDirection(
        riccati_frame(x),
        {"A": a, "M": b, "Q": c},
    )
    canonicalization = ConstraintCanonicalization(
        observer_parameters=(r, d),
        constraints=(
            a + b * r + c * r**2,
            a + b * (r + d) + c * (r + d) ** 2,
        ),
    )
    connection = canonicalization.induced_connection(
        {a: a_dot, b: b_dot, c: c_dot}
    )

    # On the canonical leaf the Riccati polynomial is
    # c (x-r) (x-r-d).  Substitute x=r+d*y only after the observer has been
    # selected; the affine chart is a representation shadow, not primitive data.
    canonical_leaf = {
        a: c * r * (r + d),
        b: -c * (2 * r + d),
    }
    r_dot = sp.simplify(connection.rate(r).subs(canonical_leaf))
    d_dot = sp.simplify(connection.rate(d).subs(canonical_leaf))
    kappa = sp.expand(c * d)

    x_dot = sp.expand(
        physical.apply(x).subs(x, r + d * y).subs(canonical_leaf)
    )
    y_dot = sp.simplify((x_dot - r_dot - y * d_dot) / d)
    expected_y_dot = sp.expand(
        -r_dot / d
        + (-kappa - d_dot / d) * y
        + kappa * y**2
    )
    assert sp.simplify(y_dot - expected_y_dot) == 0

    observed_frame = riccati_frame(y)
    observed = ProcessDirection(
        observed_frame,
        {
            "A": -r_dot / d,
            "M": -kappa - d_dot / d,
            "Q": kappa,
        },
        label="moving affine Riccati presentation",
    )
    assert sp.simplify(observed.apply(y) - y_dot) == 0

    renormalizable = ProcessDirection(
        observed_frame,
        {
            "A": -r_dot / d,
            "M": -kappa - d_dot / d,
        },
        label="affine observer tangent",
    )
    resonant = ProcessDirection(observed_frame, {}, label="no Riccati resonance")
    completion = ProcessDirection(
        observed_frame,
        {"Q": kappa},
        label="quadratic completion residual",
    )
    residual = sp.simplify(
        observed.apply(y)
        - renormalizable.apply(y)
        - resonant.apply(y)
        - completion.apply(y)
    )
    decomposition = CanonicalDecomposition(
        source=observed,
        renormalizable=renormalizable,
        resonant=resonant,
        completion=completion,
        certificate=residual,
        label="restricted affine Riccati split",
    )

    assert decomposition.certificate == 0
    assert sp.simplify(decomposition.completion.coefficient("Q") - kappa) == 0
    assert decomposition.completion.coefficient("A") == 0
    assert decomposition.completion.coefficient("M") == 0

    # CLASSICAL SHADOW: only after the restricted decomposition do we identify
    # the minimal completed bracket table with the standard Riccati sl(2).
    assert sp.expand(observed_frame.commutator("A", "M", y) - 1) == 0
    assert sp.expand(observed_frame.commutator("A", "Q", y) - 2 * y) == 0
    assert sp.expand(observed_frame.commutator("M", "Q", y) - y**2) == 0
