"""Galilean III: Hamiltonian generators retain a central mass residual invisible to phase-space action.

Question
--------
Galilean II proved that bare character pullback cannot create the massive affine
energy-momentum shift.  Does an independent Hamiltonian realization expose a
specific residual that the frozen finite-family API is currently erasing?

Primitive data
--------------
Use one canonical phase-space pair ``(x,p)``, time ``t``, and nonzero mass ``m``.
The free-particle Hamiltonian and the standard translation/boost generators are

    H = p^2/(2m),
    P = p,
    K = m x - t p.

The canonical Poisson bracket is used only inside this mathematical vignette;
there is no public Poisson or cocycle API.

Shakespeare reconstruction
---------------------------
The generators satisfy

    {K,H} = P,
    {K,P} = m.

The second relation is the key pressure.  ``m`` is central: it has zero
Hamiltonian vector field on ``(x,p)``.  Therefore the visible phase-space flows
of boost and spatial translation commute even though their Hamiltonian
generators retain the nonzero residual ``m``.

The finite boost flow generated by ``K`` is

    x -> x - v t,
    p -> p - m v,

and hence

    H -> H - v p + (1/2) m v^2.

Thus the translation-character labels transform affinely as

    (p,H) -> (p-mv, H-vp+(1/2)mv^2),

which moves the rest label ``(0,0)``.  This is exactly the kind of shift that
Galilean II proved cannot arise from ordinary character pullback.

Calibration statement
---------------------
Passing this file certifies that:

1. the free-particle boost generator is conserved;
2. ``{K,H}=P`` and ``{K,P}=m`` exactly;
3. the residual ``m`` generates no visible canonical phase-space motion;
4. boost and spatial-translation phase-space maps commute despite the nonzero
   generator-level residual;
5. the finite boost induces the mass-dependent affine momentum/energy shift and
   preserves the free-particle dispersion relation.

New reusable abstraction
-------------------------
None yet.  This is the second Galilean pressure on the same frozen boundary, not
an independent second mathematical organism.

Unresolved manual choice
------------------------
The pair of Galilean II/III results makes a central residual/cocycle object a
serious candidate, but the project should still seek one independent calibration
before promoting such an object to the public API.  Magnetic translations are a
natural future red-team candidate.

Boundary
--------
This file does not implement the Galilei group, projective/unitary
representations, group cohomology, or a general symplectic/Poisson framework.
It isolates one exact residual and the information lost when Hamiltonian
generators are replaced by their visible vector fields.

References
----------
[Bargmann-1954] V. Bargmann, "On Unitary Ray Representations of Continuous
Groups", Annals of Mathematics 59(1), 1954, 1-46.

[Arnold-1989] V. I. Arnold, *Mathematical Methods of Classical Mechanics*,
2nd ed., Springer, 1989.
"""

import sympy as sp


def _poisson(left, right, x, p):
    return sp.expand(
        sp.diff(left, x) * sp.diff(right, p)
        - sp.diff(left, p) * sp.diff(right, x)
    )


def test_hamiltonian_realization_exposes_mass_as_central_residual():
    x, p, t, v, a = sp.symbols("x p t v a", real=True)
    m = sp.symbols("m", nonzero=True, real=True)

    H = p**2 / (2 * m)
    P = p
    K = m * x - t * p

    assert sp.simplify(_poisson(K, H, x, p) - P) == 0
    assert sp.simplify(_poisson(K, P, x, p) - m) == 0
    assert sp.simplify(sp.diff(K, t) + _poisson(K, H, x, p)) == 0

    # The central residual has no visible Hamiltonian vector field.
    assert _poisson(x, m, x, p) == 0
    assert _poisson(p, m, x, p) == 0

    # Finite phase-space actions: spatial translation and boost commute visibly.
    def translate(state):
        state_x, state_p = state
        return (sp.expand(state_x + a), state_p)

    def boost(state):
        state_x, state_p = state
        return (sp.expand(state_x - v * t), sp.expand(state_p - m * v))

    left = boost(translate((x, p)))
    right = translate(boost((x, p)))
    assert all(sp.simplify(l - r) == 0 for l, r in zip(left, right))

    boosted_p = sp.expand(p - m * v)
    boosted_H = sp.expand(boosted_p**2 / (2 * m))
    expected_H = sp.expand(H - v * p + sp.Rational(1, 2) * m * v**2)
    assert sp.simplify(boosted_H - expected_H) == 0

    # The rest label moves: ordinary pullback could not do this in Galilean II.
    assert sp.simplify(boosted_p.subs(p, 0) + m * v) == 0
    assert sp.simplify(boosted_H.subs(p, 0) - sp.Rational(1, 2) * m * v**2) == 0

    # The free-particle dispersion relation is preserved by the affine label shift.
    assert sp.simplify(boosted_H - boosted_p**2 / (2 * m)) == 0
