"""Restricted Kepler module: renormalization, resonance, and function completion.

Question
--------
Does ``CanonicalDecomposition`` remain meaningful when the restricted
representation is a finite function module rather than a Lie algebra of state
transformations?

Primitive data
--------------
Use the Kepler shape family

    rho_K(psi) = alpha + b*cos(psi)

with canonical operator

    L_K = R^2 + 1,
    R   = d/dpsi.

The restricted observer module is

    K1 = span{1, cos(psi), sin(psi)}.

For the perturbation generated by ``rho_K**2`` we do not preload the final
constant/precession/second-harmonic interpretation.  The test expands the
forcing in exact Fourier modes and asks what the canonical operator does to each
mode.

Classical / theory lineage
--------------------------
The current AEG Analysis note predicts the local split

    n=0    -> parameter renormalization,
    n=1    -> resonant observer transport,
    n=2    -> representation completion.

For the specific ``r^-3``-type forcing, ``rho_K**2`` contains exactly those
three sectors.  This test treats that note as the calibration target, not as a
claim of general perturbation theory.

Shakespeare reconstruction
---------------------------
A one-generator ``ProcessFrame`` realizes ``R`` and verifies that ``K1`` is a
finite process-function module.  The forcing is decomposed exactly as

    c0 + c1*cos(psi) + c2*cos(2*psi).

The operator ``L_K`` distinguishes their roles:

    L_K(1)          = 1,
    L_K(cos psi)    = 0,
    L_K(cos 2 psi) = -3 cos 2 psi.

Thus the constant direction is directly renormalizable, the first harmonic is a
kernel/resonance direction that must be handled by moving observer parameters,
and the second harmonic lies outside ``K1`` even though ``L_K`` is invertible on
it.  If the representation itself is required to close under the perturbed
shape language, the minimal function-module extension is

    K2 = span{1, cos psi, sin psi, cos 2 psi, sin 2 psi}.

API pressure
------------
This calibration deliberately does **not** force the current algebraic
``Canonicalization`` object to represent the Kepler orthogonality/osculation
gauge.  That would hide a real distinction.  The test instead establishes that
the evidence-bearing ``CanonicalDecomposition`` carrier is already generic
across Lie and function-module examples, while a second canonicalization backend
will need independent justification.

Calibration statement
---------------------
Passing this file certifies that:

1. the restricted Kepler shape language is a finite ``R`` process module;
2. the squared shape forcing splits exactly into n=0, n=1, and n=2 sectors;
3. ``L_K`` classifies those sectors as range, kernel/resonance, and invertible
   complement respectively;
4. ``CanonicalDecomposition`` records that split without assuming a Lie carrier;
5. the n=1 coefficient implies the first-order apsidal observer rate
   ``varpi_dot = epsilon*alpha`` in the convention of the theory note; and
6. adjoining the second harmonic yields the minimal five-dimensional Fourier
   module closed under ``R`` through degree two.

Boundary
--------
This is a first-order restricted-shape calibration, not a general perturbed
Kepler solver.  It does not implement osculating elements, a generic projection
metric, a stationary canonicalization API, or a universal module-completion
search.
"""

import sympy as sp

from aeg_shakespeare.analysis.decomposition import CanonicalDecomposition
from aeg_shakespeare.analysis.module import ProcessFunctionModule
from aeg_shakespeare.process.local import ProcessFrame


def rotation_frame(psi):
    return ProcessFrame(
        assignments=(psi,),
        generators={"R": {psi: sp.S.One}},
    )


def kepler_k1_module(psi):
    return ProcessFunctionModule(
        basis=(1, sp.cos(psi), sp.sin(psi)),
        actions={
            "R": (
                (0, 0, 0),
                (0, 0, -1),
                (0, 1, 0),
            )
        },
    )


def kepler_k2_module(psi):
    return ProcessFunctionModule(
        basis=(
            1,
            sp.cos(psi),
            sp.sin(psi),
            sp.cos(2 * psi),
            sp.sin(2 * psi),
        ),
        actions={
            "R": (
                (0, 0, 0, 0, 0),
                (0, 0, -1, 0, 0),
                (0, 1, 0, 0, 0),
                (0, 0, 0, 0, -2),
                (0, 0, 0, 2, 0),
            )
        },
    )


def apply_kepler_operator(frame, expr):
    first = frame.apply("R", expr)
    second = frame.apply("R", first)
    return sp.expand(second + expr)


def test_restricted_kepler_module_is_exactly_r_closed():
    psi = sp.Symbol("psi", real=True)
    frame = rotation_frame(psi)
    k1 = kepler_k1_module(psi)

    assert k1.dimension == 3
    assert k1.verify(frame)


def test_squared_kepler_shape_has_canonical_three_sector_split():
    psi = sp.Symbol("psi", real=True)
    alpha, b, epsilon = sp.symbols("alpha b epsilon")
    frame = rotation_frame(psi)

    rho0 = alpha + b * sp.cos(psi)
    forcing = sp.expand_trig(sp.expand(rho0**2))

    c0 = alpha**2 + b**2 / 2
    resonant = 2 * alpha * b * sp.cos(psi)
    completion = b**2 * sp.cos(2 * psi) / 2
    expected = sp.expand_trig(c0 + resonant + completion)
    assert sp.trigsimp(forcing - expected) == 0

    # The canonical operator itself distinguishes the three roles.
    assert sp.simplify(apply_kepler_operator(frame, sp.S.One) - 1) == 0
    assert sp.simplify(apply_kepler_operator(frame, sp.cos(psi))) == 0
    assert sp.simplify(
        apply_kepler_operator(frame, sp.cos(2 * psi))
        + 3 * sp.cos(2 * psi)
    ) == 0

    source = sp.expand_trig(epsilon * forcing)
    renormalizable_part = sp.expand(epsilon * c0)
    resonant_part = sp.expand(epsilon * resonant)
    completion_part = sp.expand_trig(epsilon * completion)
    residual = sp.trigsimp(
        source
        - renormalizable_part
        - resonant_part
        - completion_part
    )
    decomposition = CanonicalDecomposition(
        source=source,
        renormalizable=renormalizable_part,
        resonant=resonant_part,
        completion=completion_part,
        certificate=residual,
        label="restricted Kepler Fourier split",
    )
    assert decomposition.certificate == 0

    # In the theory note's first-order moving-shape convention,
    # 2*b*varpi_dot*cos(psi) matches the resonant forcing coefficient.
    varpi_dot = sp.simplify(
        (epsilon * 2 * alpha * b) / (2 * b)
    )
    assert sp.simplify(varpi_dot - epsilon * alpha) == 0


def test_second_harmonic_is_minimal_function_module_completion():
    psi = sp.Symbol("psi", real=True)
    frame = rotation_frame(psi)
    k1 = kepler_k1_module(psi)
    k2 = kepler_k2_module(psi)

    assert k1.verify(frame)
    assert k2.verify(frame)
    assert k2.dimension == 5

    # cos(2 psi) is genuinely outside span{1, cos psi, sin psi}; exact Fourier
    # orthogonality gives a simple certificate without selecting sample points.
    projection_coefficients = tuple(
        sp.simplify(
            sp.integrate(
                sp.cos(2 * psi) * basis_item,
                (psi, -sp.pi, sp.pi),
            )
        )
        for basis_item in k1.basis
    )
    assert projection_coefficients == (0, 0, 0)

    # R forces the companion sin(2 psi), so adding only cos(2 psi) would not be
    # process-closed; the two-mode extension is the minimal R-closed completion.
    assert frame.apply("R", sp.cos(2 * psi)) == -2 * sp.sin(2 * psi)
    assert frame.apply("R", sp.sin(2 * psi)) == 2 * sp.cos(2 * psi)
