"""Coupled scalar processes: relative-scale transport and minimal matrix completion.

Question
--------
Does the canonical-observer vertical slice survive the first genuinely
multivariable pressure test, where two scalar A/M registers are coupled by
cross-process directions that cannot be absorbed by independent affine rulers?

Primitive data
--------------
Use two assignments ``x,y`` with the linear process

    x_dot = b11*x + b12*y,
    y_dot = b21*x + b22*y.

The restricted observer language starts from the independent scalar-register
algebra generated by

    A1, A2, M1=x*d/dx, M2=y*d/dy.

Cross coupling introduces

    E12=y*d/dx,
    E21=x*d/dy.

The observer may rescale ``x`` relative to ``y`` by ``rho``.  For positive
cross-couplings, local canonicalization balances their transformed magnitudes:

    b12*rho = b21/rho,

or equivalently ``b12*rho**2-b21=0``.

No ``GL(2)`` normal form, matrix basis, opposite shear, or completed
``aff(2)`` algebra is supplied as a target.

Classical lineage
-----------------
A two-dimensional linear vector field is conventionally encoded by a matrix,
and the diagonal and off-diagonal matrix units generate the corresponding
matrix Lie algebra under commutator.  Matrix Lie groups/algebras and the
identification of matrix commutators with infinitesimal linear transformations
are standard; see [Hall-2015], especially Chapters 2--3.  The interpretation of
ordinary equations of motion as vector-field flows is standard classical
mechanics; see [Arnold-1989], Newtonian Mechanics, pp. 15--52.

This test reverses that order.  It does not start with a full matrix algebra and
then diagonalize it.  It starts with two independent scalar rulers and asks which
cross directions the coupled process itself forces into the representation.

Shakespeare reconstruction
---------------------------
``ConstraintCanonicalization`` differentiates the balance condition and induces
the relative-scale observer rate.  With the gauge choice ``u=rho*x, v=y`` the
connection contributes only to the diagonal ``M1`` direction.  On the canonical
leaf, both cross coefficients become equal, but the cross directions themselves
remain outside the original independent-register observer algebra.

The exact decomposition therefore separates

    diagonal ruler motion -> renormalizable / observer transport,
    E12,E21              -> representation completion.

Under Shakespeare's existing commutator convention

    [X,Y] = X(Y) - Y(X),

the cross bracket is

    [E12,E21] = M2 - M1.

This sign is fixed by the executable convention.  One line in the current v0.2
theory note has the opposite sign; that discrepancy is a documentation error,
not an alternative mathematical result.  The generated algebra conclusion is
unchanged.

Calibration statement
---------------------
Passing this file certifies that:

1. one ``ProcessDirection`` represents the coupled two-register process;
2. balancing the two cross couplings induces the expected relative-scale
   connection law;
3. connection transport remains inside the diagonal register algebra;
4. bidirectional cross coupling survives as a genuine completion residual;
5. the cross directions close with the diagonal rulers as the full matrix
   algebra; and
6. with only one cross direction present, brackets remain in the corresponding
   triangular matrix algebra rather than forcing the missing opposite shear.

Proof map
---------
1. ``test_relative_scale_canonicalization_induces_connection`` differentiates
   ``b12*rho**2-b21=0`` and checks the exact logarithmic relative-scale rate.
2. ``test_bidirectional_cross_coupling_forces_matrix_completion`` checks the
   original assignment equations, moves to the balanced observer frame,
   certifies the decomposition residual as exactly zero, and only then evaluates
   the bracket table that generates the matrix/affine classical shadow.
3. ``test_one_way_cross_coupling_stays_triangular`` is the minimality red team:
   the one-sided shear closes without manufacturing the opposite shear.

Boundary
--------
This calibration fixes a positive-coupling sector and one residual gauge by
holding the second scale fixed.  It does not define a general ``GL(n)`` observer,
a matrix normal-form search, a proof that every variable mixing forces full
``aff(n)``, or a universal completion algorithm.  The balance condition is a
project-specific canonicalization used to calibrate transport.  The Shakespeare
interpretation -- independent rulers first, matrix closure only when forced --
is not attributed to the classical references.

References
----------
[Hall-2015] Brian C. Hall, *Lie Groups, Lie Algebras, and Representations: An
Elementary Introduction*, 2nd ed., Graduate Texts in Mathematics 222, Springer,
2015, Chapters 2--3; DOI 10.1007/978-3-319-13467-3.

[Arnold-1989] V. I. Arnold, *Mathematical Methods of Classical Mechanics*,
2nd ed., Graduate Texts in Mathematics 60, Springer, 1989, Newtonian Mechanics,
"Investigation of the equations of motion," pp. 15--52;
DOI 10.1007/978-1-4757-2063-1.
"""

import sympy as sp

from process_geometry.experimental import (
    CanonicalDecomposition,
    ConstraintCanonicalization,
)
from process_geometry.process.local import ProcessDirection, ProcessFrame


def coupled_frame(x, y):
    return ProcessFrame(
        assignments=(x, y),
        generators={
            "A1": {x: 1, y: 0},
            "A2": {x: 0, y: 1},
            "M1": {x: x, y: 0},
            "M2": {x: 0, y: y},
            "E12": {x: y, y: 0},
            "E21": {x: 0, y: x},
        },
    )


def test_relative_scale_canonicalization_induces_connection():
    b12, b21, rho = sp.symbols("b12 b21 rho", positive=True)
    b12_dot, b21_dot = sp.symbols("b12_dot b21_dot")

    canonicalization = ConstraintCanonicalization(
        observer_parameters=(rho,),
        constraints=(b12 * rho**2 - b21,),
        label="balanced cross coupling",
    )
    connection = canonicalization.induced_connection(
        {b12: b12_dot, b21: b21_dot}
    )
    assert connection.certified

    expected_log_rate = sp.Rational(1, 2) * (
        b21_dot / b21 - b12_dot / b12
    )
    on_leaf = {b21: b12 * rho**2}
    assert sp.simplify(
        connection.rate(rho).subs(on_leaf) / rho
        - expected_log_rate.subs(on_leaf)
    ) == 0


def test_bidirectional_cross_coupling_forces_matrix_completion():
    x, y, u, v = sp.symbols("x y u v")
    b11, b22 = sp.symbols("b11 b22")
    b12, b21, rho = sp.symbols("b12 b21 rho", positive=True)
    b12_dot, b21_dot = sp.symbols("b12_dot b21_dot")

    physical = ProcessDirection(
        coupled_frame(x, y),
        {
            "M1": b11,
            "M2": b22,
            "E12": b12,
            "E21": b21,
        },
        label="coupled scalar process",
    )
    assert physical.apply(x) == b11 * x + b12 * y
    assert physical.apply(y) == b21 * x + b22 * y

    canonicalization = ConstraintCanonicalization(
        observer_parameters=(rho,),
        constraints=(b12 * rho**2 - b21,),
    )
    connection = canonicalization.induced_connection(
        {b12: b12_dot, b21: b21_dot}
    )
    rho_dot = connection.rate(rho)

    # Gauge choice u=rho*x, v=y. Relative-scale transport adds rho_dot/rho to
    # M1; it does not manufacture E12 or E21.
    observed_frame = coupled_frame(u, v)
    observed = ProcessDirection(
        observed_frame,
        {
            "M1": b11 + rho_dot / rho,
            "M2": b22,
            "E12": b12 * rho,
            "E21": b21 / rho,
        },
        label="balanced moving register frame",
    )

    canonical_leaf = {b21: b12 * rho**2}
    assert sp.simplify(
        observed.coefficient("E12")
        - observed.coefficient("E21").subs(canonical_leaf)
    ) == 0

    renormalizable = ProcessDirection(
        observed_frame,
        {
            "M1": b11 + rho_dot / rho,
            "M2": b22,
        },
        label="independent-register transport",
    )
    resonant = ProcessDirection(observed_frame, {}, label="no resonance in this test")
    completion = ProcessDirection(
        observed_frame,
        {
            "E12": b12 * rho,
            "E21": b21 / rho,
        },
        label="cross-coupling completion",
    )
    residuals = tuple(
        sp.simplify(
            observed.apply(symbol)
            - renormalizable.apply(symbol)
            - resonant.apply(symbol)
            - completion.apply(symbol)
        )
        for symbol in (u, v)
    )
    decomposition = CanonicalDecomposition(
        source=observed,
        renormalizable=renormalizable,
        resonant=resonant,
        completion=completion,
        certificate=residuals,
        label="diagonal transport plus cross completion",
    )
    assert decomposition.certificate == (0, 0)

    # CLASSICAL SHADOW: the exact brackets identify the matrix closure only
    # after the restricted observer decomposition has exposed the cross residual.
    assert observed_frame.commutator("E12", "E21", u) == -u
    assert observed_frame.commutator("E12", "E21", v) == v
    assert observed_frame.commutator("M1", "E12", u) == -v
    assert observed_frame.commutator("M2", "E12", u) == v
    assert observed_frame.commutator("M1", "E21", v) == u
    assert observed_frame.commutator("M2", "E21", v) == -u

    # Adding translations yields the affine closure: cross directions transport
    # one register's translation into the other.
    assert observed_frame.commutator("E12", "A2", u) == -1
    assert observed_frame.commutator("E21", "A1", v) == -1


def test_one_way_cross_coupling_stays_triangular():
    u, v = sp.symbols("u v")
    frame = coupled_frame(u, v)

    # The subalgebra <M1,M2,E12> closes without producing E21.
    assert frame.commutator("M1", "M2", u) == 0
    assert frame.commutator("M1", "M2", v) == 0
    assert frame.commutator("M1", "E12", u) == -v
    assert frame.commutator("M2", "E12", u) == v
    assert frame.commutator("M1", "E12", v) == 0
    assert frame.commutator("M2", "E12", v) == 0
