"""Restricted Kepler module: renormalization, resonance, and function completion.

Question
--------
Does ``CanonicalDecomposition`` remain meaningful when the restricted
representation is a finite function module rather than a Lie algebra of state
transformations?

Primitive data
--------------
Use the Kepler shape family

    rho_K(psi) = alpha + b*cos(psi)

with the canonical differential operator

    L_K = R^2 + 1,
    R   = d/dpsi.

The restricted observer module is

    K1 = span{1, cos(psi), sin(psi)}.

For the perturbation generated by ``rho_K**2`` the program is not supplied with
pre-labeled ``renormalization``, ``precession``, or ``second-harmonic`` pieces.
It expands the forcing exactly and asks how ``L_K`` acts on the resulting modes.
No full osculating-element chart, Fourier transform, orbital-element equations,
or completed degree-two module is supplied.

Classical lineage
-----------------
The inverse-square central-force problem and its conic-orbit description are
standard classical mechanics; a conventional presentation is Goldstein, Poole,
and Safko, Chapter 3, "The Central Force Problem" [Goldstein-Poole-Safko-2002].
Perturbative variation of nearly integrable mechanical systems is classical; see
Arnold's introduction to perturbation theory [Arnold-1989].  The elementary
trigonometric product/square identities used to expose the constant, first, and
second harmonics are tabulated in NIST DLMF §4.21 [DLMF-4.21].

The **Shakespeare interpretation** tested here is more specific and is not a
claim made by those sources: a restricted Kepler shape language should first be
viewed as a low-dimensional process module, after which forcing directions are
classified by their relation to the canonical operator and the current module.

Project-theory lineage
----------------------
The current AEG Analysis programme predicts the local split

    n=0    -> parameter renormalization,
    n=1    -> resonant observer transport,
    n=2    -> representation completion.

For the specific ``rho_K**2`` forcing, those three sectors are all present.  The
test treats this as a bounded calibration target, not as a general theorem of
celestial perturbation theory.

Shakespeare reconstruction
---------------------------
A one-generator ``ProcessFrame`` realizes ``R`` and verifies that ``K1`` is a
finite process-function module.  The forcing is decomposed exactly as

    c0 + c1*cos(psi) + c2*cos(2*psi).

The operator ``L_K`` distinguishes their roles:

    L_K(1)          = 1,
    L_K(cos psi)    = 0,
    L_K(cos 2 psi) = -3 cos 2 psi.

Thus the constant direction is directly renormalizable, the first harmonic is a
kernel/resonance direction represented by moving shape parameters, and the
second harmonic lies outside ``K1`` even though ``L_K`` is invertible on it.  If
the *representation itself* must remain closed under the perturbed shape
language, the smallest ``R``-closed extension containing that new harmonic is

    K2 = span{1, cos psi, sin psi, cos 2 psi, sin 2 psi}.

API pressure
------------
This calibration deliberately does **not** force
``ConstraintCanonicalization`` to represent the Kepler orthogonality/osculation
gauge.  Doing so would make an exact-equation backend masquerade as the generic
notion of canonicalization.  The test instead asks only whether the
evidence-bearing ``CanonicalDecomposition`` result shape survives a change from
Lie directions to a function-module carrier.

Calibration statement
---------------------
Passing this file certifies that:

1. the restricted Kepler shape language is a finite ``R`` process module;
2. the squared shape forcing splits exactly into n=0, n=1, and n=2 sectors;
3. ``L_K`` classifies those sectors as range, kernel/resonance, and invertible
   complement respectively;
4. ``CanonicalDecomposition`` records that split without assuming a Lie carrier;
5. matching the n=1 coefficient to the stated first-order moving-shape ansatz
   gives ``varpi_dot = epsilon*alpha`` in this calibration; and
6. adjoining the second harmonic yields the minimal five-dimensional Fourier
   module closed under ``R`` through degree two.

Proof map
---------
1. ``test_restricted_kepler_module_is_exactly_r_closed`` verifies the declared
   three-dimensional ``R`` action table against the symbolic process frame.
2. ``test_squared_kepler_shape_has_canonical_three_sector_split`` derives the
   exact harmonic decomposition, checks the three ``L_K`` actions, certifies the
   zero decomposition residual, and then matches the resonant coefficient to
   the stated first-order observer-rate convention.
3. ``test_second_harmonic_is_minimal_function_module_completion`` uses exact
   Fourier orthogonality to show ``cos(2 psi)`` is outside ``K1`` and checks that
   ``R`` forces its ``sin(2 psi)`` companion, yielding the minimal degree-two
   closed module.

Boundary
--------
This is a first-order restricted-shape calibration, not a general perturbed
Kepler solver, a derivation of arbitrary apsidal precession, or a theorem that
all Kepler perturbations split by harmonic number in this way.  It does not
implement osculating elements, a generic projection metric, a stationary
canonicalization API, or a universal module-completion search.  The
``varpi_dot`` statement is conditional on the explicit first-order moving-shape
ansatz stated in this essay and checked algebraically here.

For the process-language ledger, the declared task is the finite exact
decomposition and reconstruction of one supplied first-order forcing in the
bounded ``R``-module.  A trajectory history, raw-history unfolding,
topological cover, analytic developing cover, and continuation-semantic task
quotient are not required for that task.  The zero decomposition residual is
the exact reconstruction certificate.  These axes are therefore explicitly
``not applicable``, not unexamined.

References
----------
[Goldstein-Poole-Safko-2002] Herbert Goldstein, Charles P. Poole Jr., John L.
Safko, *Classical Mechanics*, 3rd ed., Addison-Wesley, 2002, Chapter 3,
"The Central Force Problem," ISBN 0-201-65702-3.

[Arnold-1989] V. I. Arnold, *Mathematical Methods of Classical Mechanics*,
2nd ed., Graduate Texts in Mathematics 60, Springer, 1989, "Introduction to
perturbation theory," pp. 271--300; DOI 10.1007/978-1-4757-2063-1.

[DLMF-4.21] NIST Digital Library of Mathematical Functions, §4.21,
"Identities" for trigonometric functions, especially squares/products and
multiple-angle identities, https://dlmf.nist.gov/4.21 .
"""

import sympy as sp

from process_geometry.experimental import CanonicalDecomposition
from process_geometry.analysis.module import ProcessFunctionModule
from process_geometry.process.local import ProcessFrame


def rotation_frame(psi):
    return ProcessFrame(
        assignments=(psi,),
        generators={"R": {psi: sp.S.One}},
    )


def kepler_k1_module(psi):
    return ProcessFunctionModule(
        basis=(1, sp.cos(psi), sp.sin(psi)),
        actions={
            "R": (
                (0, 0, 0),
                (0, 0, -1),
                (0, 1, 0),
            )
        },
    )


def kepler_k2_module(psi):
    return ProcessFunctionModule(
        basis=(
            1,
            sp.cos(psi),
            sp.sin(psi),
            sp.cos(2 * psi),
            sp.sin(2 * psi),
        ),
        actions={
            "R": (
                (0, 0, 0, 0, 0),
                (0, 0, -1, 0, 0),
                (0, 1, 0, 0, 0),
                (0, 0, 0, 0, -2),
                (0, 0, 0, 2, 0),
            )
        },
    )


def apply_kepler_operator(frame, expr):
    first = frame.apply("R", expr)
    second = frame.apply("R", first)
    return sp.expand(second + expr)


def test_restricted_kepler_module_is_exactly_r_closed():
    psi = sp.Symbol("psi", real=True)
    frame = rotation_frame(psi)
    k1 = kepler_k1_module(psi)

    assert k1.dimension == 3
    assert k1.verify(frame)


def test_squared_kepler_shape_has_canonical_three_sector_split():
    psi = sp.Symbol("psi", real=True)
    alpha, b, epsilon = sp.symbols("alpha b epsilon")
    frame = rotation_frame(psi)

    rho0 = alpha + b * sp.cos(psi)
    forcing = sp.expand_trig(sp.expand(rho0**2))

    c0 = alpha**2 + b**2 / 2
    resonant = 2 * alpha * b * sp.cos(psi)
    completion = b**2 * sp.cos(2 * psi) / 2
    expected = sp.expand_trig(c0 + resonant + completion)
    assert sp.trigsimp(forcing - expected) == 0

    # The canonical operator itself distinguishes the three roles.
    assert sp.simplify(apply_kepler_operator(frame, sp.S.One) - 1) == 0
    assert sp.simplify(apply_kepler_operator(frame, sp.cos(psi))) == 0
    assert sp.simplify(
        apply_kepler_operator(frame, sp.cos(2 * psi))
        + 3 * sp.cos(2 * psi)
    ) == 0

    source = sp.expand_trig(epsilon * forcing)
    renormalizable_part = sp.expand(epsilon * c0)
    resonant_part = sp.expand(epsilon * resonant)
    completion_part = sp.expand_trig(epsilon * completion)
    residual = sp.trigsimp(
        source
        - renormalizable_part
        - resonant_part
        - completion_part
    )
    decomposition = CanonicalDecomposition(
        source=source,
        renormalizable=renormalizable_part,
        resonant=resonant_part,
        completion=completion_part,
        certificate=residual,
        label="restricted Kepler Fourier split",
    )
    assert decomposition.certificate == 0

    # PROJECT-THEORY SHADOW: in the stated first-order moving-shape convention,
    # 2*b*varpi_dot*cos(psi) matches the resonant forcing coefficient.
    varpi_dot = sp.simplify(
        (epsilon * 2 * alpha * b) / (2 * b)
    )
    assert sp.simplify(varpi_dot - epsilon * alpha) == 0


def test_second_harmonic_is_minimal_function_module_completion():
    psi = sp.Symbol("psi", real=True)
    frame = rotation_frame(psi)
    k1 = kepler_k1_module(psi)
    k2 = kepler_k2_module(psi)

    assert k1.verify(frame)
    assert k2.verify(frame)
    assert k2.dimension == 5

    # cos(2 psi) is genuinely outside span{1, cos psi, sin psi}; exact Fourier
    # orthogonality gives a certificate without selecting sample points.
    projection_coefficients = tuple(
        sp.simplify(
            sp.integrate(
                sp.cos(2 * psi) * basis_item,
                (psi, -sp.pi, sp.pi),
            )
        )
        for basis_item in k1.basis
    )
    assert projection_coefficients == (0, 0, 0)

    # R forces the companion sin(2 psi), so adding only cos(2 psi) would not be
    # process-closed; the two-mode extension is the minimal R-closed completion.
    assert frame.apply("R", sp.cos(2 * psi)) == -2 * sp.sin(2 * psi)
    assert frame.apply("R", sp.sin(2 * psi)) == 2 * sp.cos(2 * psi)
