"""Internal finite-polynomial validation and normal-form helpers.

This backend gives ``polynomial`` its narrow algebraic meaning throughout the
package: finite support in declared indeterminates with non-negative integer
exponents. It does not recognize power series, analytic closure, or the class
of functions generated by process operations.

Expressions independent of the declared indeterminates are coefficients. In
particular, a symbolic parameter may occur in a coefficient without becoming
another polynomial indeterminate. Callers that need polynomial dependence on
that parameter must declare it as an indeterminate too.
"""

from __future__ import annotations

from typing import Iterable, Sequence

import sympy as sp


def polynomial_indeterminates(
    variables: Sequence[sp.Symbol],
) -> tuple[sp.Symbol, ...]:
    """Return a checked, ordered tuple of polynomial indeterminates."""

    variables = tuple(variables)
    if any(not isinstance(variable, sp.Symbol) for variable in variables):
        raise TypeError("polynomial indeterminates must be SymPy symbols")
    if len(set(variables)) != len(variables):
        raise ValueError("polynomial indeterminates must be distinct")
    return variables


def inferred_polynomial_indeterminates(
    expressions: Iterable[sp.Expr],
) -> tuple[sp.Symbol, ...]:
    """Infer indeterminates from all free symbols in finite expressions."""

    symbols: set[sp.Symbol] = set()
    for expression in expressions:
        symbols.update(sp.sympify(expression).free_symbols)
    return tuple(sorted(symbols, key=sp.default_sort_key))


def finite_polynomial_normal_form(
    expression: sp.Expr,
    variables: Sequence[sp.Symbol],
    *,
    label: str = "expression",
) -> sp.Expr:
    """Return the expanded finite-polynomial normal form in ``variables``.

    The coefficient domain is SymPy's exact expression domain. Consequently
    expressions independent of ``variables`` act as scalars, while ``exp(x)``,
    ``sin(x)``, negative powers, rational functions, and unevaluated infinite
    sums are rejected whenever ``x`` is a declared indeterminate.
    """

    variables = polynomial_indeterminates(variables)
    expression = sp.expand(sp.sympify(expression))
    if not variables:
        return expression
    try:
        polynomial = sp.Poly(expression, *variables, domain="EX")
    except sp.PolynomialError as exc:
        raise ValueError(
            f"{label} must be a finite polynomial in the declared indeterminates"
        ) from exc
    return sp.expand(polynomial.as_expr())
