"""Sonnet 001 Phase 9B: local center-4 semantics red-team the frozen pressure detector.

Question
--------
Phase 9A replayed the Phase-8 next-layer detector exactly on center-2 -> center-3
and then, without changing its rule, marked only nine of the 2,753 Phase-8E
center-3 persistent cells for reopening under the center-4 contact layer:

    2,744 stable / 2 nonbranching pressure / 7 completion pressure.

Do the exact center-4 first-witness semantics confirm those predicted roles?  And
what process-wall language is actually required to decide the refined semantics
inside the nine pressure cells?

Primitive data
--------------
The program receives:

- the Phase-8E center-3 persistent constraint cells and their exact closure atoms;
- the nine Phase-9A pressure cells only;
- center-4 contact events generated by the same A/M contact law;
- exact multiplicative difference-constraint operations.

It does not receive a complete center-4 wall arrangement, center-4 task labels, a
fresh center-4 decision tree, deeper contact layers, or `K=13` data.

Classical lineage
-----------------
The surrounding Lonely Runner computational frontier is described in
[Sungkawichai-Trakulthongchai-2026].  The event-order branching oracle and the
interpretation of latent constraint provenance as representation state are
**Shakespeare reconstructions**, not claims of that source.

Shakespeare reconstruction
---------------------------
For each exact closure atom below one of the nine pressure cells, process contact
events in temporal order.  If the closure decides the next comparison, no new
syntax is materialized.  If one event-time comparison is unresolved, branch only
on the corresponding process-generated collision wall, tighten the exact
closure, and continue.  Stop immediately when the first-witness task is decided.

This is therefore a lazy semantic refinement rather than a Cartesian product of
all center-4 wall strata.

The union of all semantic leaves below a current persistent cell supplies its
exact center-4 task set.  Queried collision walls are separately classified as:

- genuinely new center-4 ratios; or
- latent older walls whose ratios already existed by center 3 but whose signs
  were not explicit in the Phase-8E 28-predicate signature.

Calibration statement
---------------------
Passing this bounded semantic red team certifies that:

1. the two Phase-9A nonbranching-pressure cells each have exactly one center-4
   first-witness semantic;
2. both preserve the old witness boundary and mode and shift only event rank by
   `+2`, so they are history/decoder reindexing rather than observer transport;
3. all seven Phase-9A completion-pressure cells genuinely branch, with sorted
   task multiplicities `2,2,3,3,4,4,4`;
4. the corrected center-4 canonical sectors are therefore
   `2,746 renormalizable / 0 resonant / 7 completion`;
5. the nine local expansions terminate in 107 exact semantic leaves in total;
6. every one of the seven genuine completion cases queries at least one latent
   older wall in addition to center-4 process-generated walls; and
7. the result therefore exposes a future-sufficiency distinction: the explicit
   Phase-8E task/sign signature alone is not enough for this center-4 semantic
   refinement, whereas the retained exact closure provenance supplies the
   missing latent distinctions on demand.

Proof map
---------
1. ``test_center4_local_semantics_confirm_pressure_roles_and_expose_latent_state``
   runs the lazy event-order oracle on only the nine Phase-9A pressure cells,
   checks the exact uniform/branching roles, witness reindex behavior, task
   multiplicities and semantic-leaf count, and verifies that every completion
   case requires latent older-wall information.

Boundary
--------
The queried-wall set is the union of walls encountered by the current lazy
first-witness branching procedure; it is not yet a minimum completion support.
Phase 9C must perform a task-separating minimization before any wall count is
called a minimal representation.

Likewise, `latent older wall required by the semantic oracle` does not mean that
all such signs must be stored eagerly.  The current representation retains exact
closure atoms, from which these distinctions can be materialized only when
needed.  The result establishes pressure for future-sufficient constraint
provenance, not a public `ConstraintCell` API.

No new Lonely Runner theorem or discrete observer connection is established.

References
----------
[Sungkawichai-Trakulthongchai-2026] Touch Sungkawichai, Tanupat
Trakulthongchai, "Eleven, twelve, and thirteen lonely runners,"
arXiv:2604.23906 (2026), https://arxiv.org/abs/2604.23906 .
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import sys

import pytest


RUN_FULL = os.environ.get("AEG_RUN_LR_CENTER4_SEMANTICS") == "1"
pytestmark = pytest.mark.skipif(
    not RUN_FULL,
    reason="opt-in Sonnet 001 center4 local semantic red team",
)


def _load_module():
    root = Path(__file__).parents[2]
    script_dir = root / "sonnet" / "lonely-runner" / "python"
    script_path = script_dir / "center4_semantic_redteam.py"
    sys.path.insert(0, str(script_dir))
    try:
        spec = importlib.util.spec_from_file_location(
            "sonnet_center4_semantic_redteam",
            script_path,
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(script_dir))


def test_center4_local_semantics_confirm_pressure_roles_and_expose_latent_state():
    semantic = _load_module()
    result = semantic.analyze_center4_semantic_redteam()

    assert len(result.cases) == 9
    assert len(result.uniform_cases) == 2
    assert len(result.branching_cases) == 7
    assert sorted(case.task_count for case in result.branching_cases) == [
        2, 2, 3, 3, 4, 4, 4
    ]

    assert all(case.phase9a_role == "nonbranching-pressure" for case in result.uniform_cases)
    assert all(case.same_boundary_and_mode for case in result.uniform_cases)
    assert all(case.new_tasks[0][0] - case.old_task[0] == 2 for case in result.uniform_cases)

    assert all(case.phase9a_role == "completion-pressure" for case in result.branching_cases)
    assert sum(case.semantic_leaf_count for case in result.cases) == 107
    assert all(case.new_center4_walls for case in result.branching_cases)
    assert all(case.latent_older_walls for case in result.branching_cases)
