"""Sonnet 001 Phase 9C: center-4 minimum completion and independent oracle red team.

Question
--------
Phase 9B confirms seven genuinely branching center-4 completion cells.  Its lazy
first-witness oracle may query both newly generated center-4 walls and latent
older walls.  Which distinctions are actually necessary for the task, and can
that minimum representation be checked by an independent refinement path?

Primitive data
--------------
The program receives:

- the Phase-8E 2,753 persistent center-3 constraint cells;
- the nine Phase-9A pressure cells;
- Phase-9B exact center-4 task semantics and its encountered collision-wall
  grammar;
- exact multiplicative difference-constraint operations;
- center-4 contact ratios generated by the same process law.

It does not receive a hand-picked target wall, a fresh center-4 decision tree,
`K=13` data, or a globally enumerated center-4 task table.

Classical lineage
-----------------
The surrounding Lonely Runner frontier is described in
[Sungkawichai-Trakulthongchai-2026].  Minimum task-separating wall search and the
persistent-representation interpretation are **Shakespeare reconstructions**.
The finite subset minimization is a bounded exact analogue of separating-feature
selection; no universality claim is attributed to the source.

Shakespeare reconstruction
---------------------------
For each of the seven branching cells, take the complete wall union encountered
by the Phase-9B lazy oracle.  Refine every exact closure atom by those walls,
obtain all feasible ternary sign records, and attach the independently computed
first-witness task.  Search every wall subset and retain the minimum-cardinality
subset whose projected sign record determines the task exactly.

A separate local full-stratum oracle then refines only the nine pressure cells
to the complete center-4 contact alphabet and evaluates them with the older
`pair_difference_refinement.first_witness` implementation.  This is a
post-construction truth oracle: it does not participate in representation
selection.

Calibration statement
---------------------
Passing this bounded Phase-9C calibration certifies that:

1. all seven genuine completion cells have exactly three center-4 task semantics;
2. every one has minimum wall support size one;
3. the selected primitive is the same in all seven cases,
   `u4/u3 ? 19/11` (zero-index pair `(2,3)`);
4. this ratio is genuinely new at center 4, so every minimum support has
   `(new, latent) = (1,0)`;
5. six cases already have exactly three complete raw sign classes, while one
   lazy candidate grammar has two walls / nine raw classes but still minimizes
   to the same one-wall / three-class task representation;
6. the independent local full-stratum oracle agrees exactly with the Phase-9B
   lazy task set on all nine pressure cells; and
7. in every branching cell the three signs of `u4/u3 - 19/11` each map to one
   and only one task semantic.

Proof map
---------
1. ``test_center4_minimum_completion_is_one_shared_new_ternary_wall`` checks the
   exact seven-case minimum-support profile and the universal `19/11` wall.
2. ``test_center4_local_full_stratum_oracle_confirms_lazy_tasks_and_ternary_wall``
   runs the independent post-construction oracle and checks exact task-set
   agreement plus the three-sign / three-task map.

Boundary
--------
The result is a bounded center-3 -> center-4 representation calibration.  It does
not prove that every future contact layer adds one common wall, nor that the
`19/11` primitive generalizes to other runner counts or tasks.

Most importantly, Phase 9B's latent-older-wall queries are now classified as a
**solver trace**, not a minimum-representation requirement.  Exact closure
provenance remains useful for discovery/certification, but this experiment does
not force it into the public persistent-state ontology.

No new Lonely Runner theorem or public completion API is established.

References
----------
[Sungkawichai-Trakulthongchai-2026] Touch Sungkawichai, Tanupat
Trakulthongchai, "Eleven, twelve, and thirteen lonely runners,"
arXiv:2604.23906 (2026), https://arxiv.org/abs/2604.23906 .
"""

from __future__ import annotations

from fractions import Fraction
import importlib.util
import os
from pathlib import Path
import sys

import pytest


RUN_FULL = os.environ.get("AEG_RUN_LR_CENTER4_MINIMAL_COMPLETION") == "1"
pytestmark = pytest.mark.skipif(
    not RUN_FULL,
    reason="opt-in Sonnet 001 center4 minimum-completion calibration",
)


def _load(name: str, filename: str):
    root = Path(__file__).parents[2]
    script_dir = root / "sonnet" / "lonely-runner" / "python"
    script_path = script_dir / filename
    sys.path.insert(0, str(script_dir))
    try:
        spec = importlib.util.spec_from_file_location(name, script_path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(script_dir))


def test_center4_minimum_completion_is_one_shared_new_ternary_wall():
    completion = _load(
        "sonnet_center4_minimal_completion",
        "center4_minimal_completion.py",
    )
    result = completion.analyze_center4_minimal_completion()

    assert len(result.cases) == 7
    assert [case.task_count for case in result.cases] == [3] * 7
    assert [case.minimum_wall_count for case in result.cases] == [1] * 7
    assert [case.minimum_class_count for case in result.cases] == [3] * 7
    assert sorted(case.candidate_wall_count for case in result.cases) == [1] * 6 + [2]
    assert sorted(case.raw_class_count for case in result.cases) == [3] * 6 + [9]

    selected = {case.selected_coordinates for case in result.cases}
    assert len(selected) == 1
    coordinate = next(iter(selected))[0]
    assert coordinate.pair == (2, 3)
    assert coordinate.ratio == Fraction(19, 11)

    assert all(len(case.new_center4_coordinates) == 1 for case in result.cases)
    assert all(not case.latent_older_coordinates for case in result.cases)


def test_center4_local_full_stratum_oracle_confirms_lazy_tasks_and_ternary_wall():
    oracle = _load(
        "sonnet_center4_local_full_oracle",
        "center4_local_full_oracle.py",
    )
    results = oracle.analyze_local_full_oracle()

    assert len(results) == 9
    direct_counts = sorted(len(direct) for _sig, _a, _s, direct, _lazy, _m in results)
    assert direct_counts == [1, 1] + [3] * 7

    for _signature, _atoms, _systems, direct, lazy, sign_map in results:
        assert direct == lazy
        if len(direct) == 3:
            assert [sign for sign, _tasks in sign_map] == [-1, 0, 1]
            assert all(len(tasks) == 1 for _sign, tasks in sign_map)
