"""AEG Addition -> Multiplication second-rank transition calibration.

The first vertical calibration objectified signed unit histories into reusable
translation objects ``T_a``.  This essay asks the next, harder question: what
must Multiplication objectify if it is genuinely one process rank above
Addition rather than another compressed translation?

The answer tested here is deliberately structural.  A multiplication object
``D_k`` objectifies the *uniform repeated-Addition schema*

    R_k(T_a) = T_a composed k times = T_(k a),

so its lower semantics is an endomorphism of the translation process, not one
translation object.  Pure multiplicative words lower to translation
endomorphisms.  Mixed Translation/Dilation words lower to the positive affine
monoid, where the AEG cross relation

    D_k T_a = T_(k a) D_k

is exact.  This is the first calibration in which rank lowering must preserve a
noncommutative relation between two process ranks.

The final test only connects this finite law to the existing A/M calculus and
its infinitesimal shadow ``[A, M] = A``.  It does *not* claim V5 analytic
closure: no higher-rank differential object or cross-rank variation transport
has yet been defined.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product

import sympy as sp

from process_geometry.function_theory.am import AMFunctionTheory, AMState
from process_geometry.process.history import ProcessWord


@dataclass(frozen=True)
class TranslationObject:
    """Rank-one Addition object, with semantics ``x -> x + amount``."""

    amount: int

    def compose(self, other: "TranslationObject") -> "TranslationObject":
        return TranslationObject(self.amount + other.amount)

    def apply(self, value: int) -> int:
        return value + self.amount


@dataclass(frozen=True)
class RepeatedAdditionSchema:
    """Lower-rank process schema objectified as one Multiplication primitive.

    The schema is intentionally parametric in the translation object.  A fixed
    composite such as ``T_2 T_2 T_2 = T_6`` is not enough to identify the
    multiplicative process because different repetition counts can agree on one
    chosen input translation and disagree on another.
    """

    repetitions: int

    def __post_init__(self) -> None:
        if self.repetitions < 1:
            raise ValueError("this AEG dilation calibration uses positive factors")

    def apply(self, translation: TranslationObject) -> TranslationObject:
        result = TranslationObject(0)
        for _ in range(self.repetitions):
            result = result.compose(translation)
        return result


@dataclass(frozen=True)
class MultiplicationPrimitive:
    """Rank-two objectification of one uniform repeated-Addition schema."""

    factor: int

    def __post_init__(self) -> None:
        if self.factor < 1:
            raise ValueError("this AEG dilation calibration uses positive factors")

    def act_on_translation(self, translation: TranslationObject) -> TranslationObject:
        return TranslationObject(self.factor * translation.amount)

    def apply(self, value: int) -> int:
        return self.factor * value


def objectify_multiplication(schema: RepeatedAdditionSchema) -> MultiplicationPrimitive:
    """Promote the whole additive action schema, not one of its outputs."""

    return MultiplicationPrimitive(schema.repetitions)


@dataclass(frozen=True)
class TranslationEndomorphism:
    """Lower semantic target for a pure multiplicative higher-rank word."""

    scale: int

    def apply(self, translation: TranslationObject) -> TranslationObject:
        return TranslationObject(self.scale * translation.amount)

    def then(self, later: "TranslationEndomorphism") -> "TranslationEndomorphism":
        # ``then`` follows ProcessWord chronology: self first, later second.
        return TranslationEndomorphism(later.scale * self.scale)


def lower_multiplicative_history(
    history: ProcessWord[MultiplicationPrimitive],
) -> TranslationEndomorphism:
    """Interpret every pure multiplicative word as an endomorphism of Addition."""

    result = TranslationEndomorphism(1)
    for primitive in history:
        result = result.then(TranslationEndomorphism(primitive.factor))
    return result


@dataclass(frozen=True)
class AffineTranslationAction:
    """Semantic completion for mixed Addition/Multiplication histories.

    ``(scale, shift)`` denotes the state action ``x -> scale*x + shift``.  This
    is the positive-integer affine monoid generated by translations and
    dilations.  It is strictly richer than the translation objects alone.
    """

    scale: int = 1
    shift: int = 0

    def apply(self, value: int) -> int:
        return self.scale * value + self.shift

    def then(self, later: "AffineTranslationAction") -> "AffineTranslationAction":
        """Compose in chronological order: apply ``self``, then ``later``."""

        return AffineTranslationAction(
            scale=later.scale * self.scale,
            shift=later.scale * self.shift + later.shift,
        )


RankTwoStep = TranslationObject | MultiplicationPrimitive


def lower_rank_two_history(history: ProcessWord[RankTwoStep]) -> AffineTranslationAction:
    """Lower every legal mixed word into the affine action semantics."""

    result = AffineTranslationAction()
    for step in history:
        if isinstance(step, TranslationObject):
            lowered = AffineTranslationAction(scale=1, shift=step.amount)
        elif isinstance(step, MultiplicationPrimitive):
            lowered = AffineTranslationAction(scale=step.factor, shift=0)
        else:  # pragma: no cover - protects the research-local semantic boundary.
            raise TypeError(f"unsupported rank-two step: {step!r}")
        result = result.then(lowered)
    return result


def interpret_rank_two(history: ProcessWord[RankTwoStep], initial: int) -> int:
    value = initial
    for step in history:
        value = step.apply(value)
    return value


def test_multiplication_objectifies_a_uniform_addition_schema_not_one_output():
    triple = RepeatedAdditionSchema(3)
    primitive = objectify_multiplication(triple)

    for amount in range(-4, 5):
        translation = TranslationObject(amount)
        assert triple.apply(translation) == TranslationObject(3 * amount)
        assert primitive.act_on_translation(translation) == triple.apply(translation)

    # One fixed additive output is insufficient evidence for the higher object:
    # 3 copies of T_2 and 2 copies of T_3 both produce T_6.
    double = RepeatedAdditionSchema(2)
    assert triple.apply(TranslationObject(2)) == double.apply(TranslationObject(3))

    # But the process schemas are different actions on the translation space.
    assert triple.apply(TranslationObject(1)) != double.apply(TranslationObject(1))


def test_pure_multiplicative_free_language_lowers_to_translation_endomorphisms():
    two = MultiplicationPrimitive(2)
    three = MultiplicationPrimitive(3)
    five = MultiplicationPrimitive(5)

    left = ProcessWord((two, three))
    right = ProcessWord((five, two))
    combined = left.compose(right)

    assert lower_multiplicative_history(left) == TranslationEndomorphism(6)
    assert lower_multiplicative_history(combined) == TranslationEndomorphism(60)
    assert lower_multiplicative_history(combined) == lower_multiplicative_history(
        left
    ).then(lower_multiplicative_history(right))

    # D_6 was not supplied as a primitive; it arises from free D_2/D_3 composition.
    unseen = lower_multiplicative_history(ProcessWord((two, three)))
    assert unseen.apply(TranslationObject(7)) == TranslationObject(42)


def test_dilation_cannot_lower_to_one_translation_object():
    dilation = MultiplicationPrimitive(2)

    # If D_2 were some translation T_b as a state map, evaluating at 0 forces
    # b = 0.  But T_0 and D_2 already disagree at 1.  The lower target must
    # therefore contain an action/endomorphism, not only translation objects.
    forced_candidate = TranslationObject(dilation.apply(0))
    assert forced_candidate == TranslationObject(0)
    assert forced_candidate.apply(1) == 1
    assert dilation.apply(1) == 2
    assert forced_candidate.apply(1) != dilation.apply(1)


def test_mixed_rank_lowering_is_compositional_for_all_small_words():
    alphabet: tuple[RankTwoStep, ...] = (
        TranslationObject(-2),
        TranslationObject(1),
        MultiplicationPrimitive(2),
        MultiplicationPrimitive(3),
    )

    for length in range(5):
        for items in product(alphabet, repeat=length):
            history = ProcessWord(tuple(items))
            lowered = lower_rank_two_history(history)
            for initial in (-3, 0, 5):
                assert lowered.apply(initial) == interpret_rank_two(history, initial)

    left = ProcessWord((TranslationObject(1), MultiplicationPrimitive(2)))
    right = ProcessWord((TranslationObject(-2), MultiplicationPrimitive(3)))
    assert lower_rank_two_history(left.compose(right)) == lower_rank_two_history(
        left
    ).then(lower_rank_two_history(right))


def test_addition_multiplication_cross_relation_lowers_soundly():
    for factor in (2, 3, 5):
        dilation = MultiplicationPrimitive(factor)
        for amount in range(-3, 4):
            translation = TranslationObject(amount)
            scaled = TranslationObject(factor * amount)

            # ProcessWord stores chronological order.  Therefore (T_a, D_k)
            # means the algebraic composite D_k T_a, while (D_k, T_ka) means
            # T_(ka) D_k.  Their lowered affine actions must coincide:
            #
            #     D_k T_a = T_(k a) D_k.
            left = ProcessWord((translation, dilation))
            right = ProcessWord((dilation, scaled))
            assert lower_rank_two_history(left) == lower_rank_two_history(right)

            for initial in (-4, 0, 7):
                assert interpret_rank_two(left, initial) == interpret_rank_two(
                    right, initial
                )


def test_additive_and_multiplicative_relations_both_survive_mixed_lowering():
    for a in range(-2, 3):
        for b in range(-2, 3):
            additive_left = ProcessWord((TranslationObject(a), TranslationObject(b)))
            additive_right = ProcessWord((TranslationObject(a + b),))
            assert lower_rank_two_history(additive_left) == lower_rank_two_history(
                additive_right
            )

    for k in (2, 3):
        for ell in (2, 5):
            multiplicative_left = ProcessWord(
                (MultiplicationPrimitive(k), MultiplicationPrimitive(ell))
            )
            multiplicative_right = ProcessWord((MultiplicationPrimitive(k * ell),))
            assert lower_rank_two_history(
                multiplicative_left
            ) == lower_rank_two_history(multiplicative_right)


def test_finite_second_rank_relation_hits_the_existing_am_calculus():
    a, v, t = sp.symbols("a v t")
    theory = AMFunctionTheory(a, v)
    state = AMState(a, v)

    # Positive integer D_k is the exact discrete sample k = exp(s) of the
    # existing finite A/M dilation S_s.  The same cross relation is therefore
    # already present in the continuous process calculus.
    for factor in (2, 3, 5):
        residual = theory.finite_relation_residual(
            state,
            amount=t,
            log_scale=sp.log(factor),
        )
        assert all(sp.simplify(component) == 0 for component in residual)

    # Its infinitesimal shadow is the existing AEG relation [A, M] = A.
    # This is only a bridge to the future V5 experiment; it is not yet a
    # cross-rank derivative/lowering commutative diagram.
    probe = a**3 * sp.exp(2 * v) + a * v + v**2
    assert sp.simplify(theory.commutator(probe) - theory.A(probe)) == 0
