"""Sonnet 001 Phase 9B: local center-4 semantics red-team the frozen pressure detector.

Question
--------
Phase 9A replayed the Phase-8 next-layer detector exactly on center-2 -> center-3
and then, without changing its rule, marked only nine of the 2,753 Phase-8E
center-3 persistent cells for reopening under the center-4 contact layer:

    2,744 stable / 2 nonbranching pressure / 7 completion pressure.

Do exact center-4 first-witness semantics confirm those predicted roles?  What
wall language does the lazy event-order oracle inspect while deciding them?

Primitive data
--------------
The program receives:

- the Phase-8E center-3 persistent constraint cells and their exact closure atoms;
- the nine Phase-9A pressure cells only;
- center-4 contact events generated by the same A/M contact law;
- exact multiplicative difference-constraint operations.

It does not receive a complete center-4 wall arrangement, center-4 task labels, a
fresh center-4 decision tree, deeper contact layers, or `K=13` data.

Classical lineage
-----------------
The surrounding Lonely Runner computational frontier is described in
[Sungkawichai-Trakulthongchai-2026].  The event-order branching oracle and its
representation interpretation are **Shakespeare reconstructions**, not claims of
that source.

Shakespeare reconstruction
---------------------------
For each exact closure atom below one of the nine pressure cells, process contact
events in temporal order.  If the closure decides the next comparison, no new
syntax is materialized.  If one event-time comparison is unresolved, branch only
on the corresponding process-generated collision wall, tighten the exact
closure, and continue.  Stop immediately when the first-witness task is decided.

This is a lazy semantic refinement rather than a Cartesian product of all
center-4 wall strata.  The union of semantic leaves below a current cell supplies
its exact center-4 task set.  Queried walls are recorded as an **algorithm trace**
only; Phase 9C and an independent local full-stratum oracle determine which of
those distinctions are actually required by the task representation.

Calibration statement
---------------------
Passing this bounded semantic red team certifies that:

1. the two Phase-9A nonbranching-pressure cells each have exactly one center-4
   first-witness semantic;
2. both preserve the old witness boundary and mode and shift only event rank by
   `+2`, so they are history/decoder reindexing rather than observer transport;
3. all seven Phase-9A completion-pressure cells genuinely branch and each has
   exactly three center-4 task semantics;
4. the corrected center-4 canonical sectors are therefore
   `2,746 renormalizable / 0 resonant / 7 completion`;
5. every branching case encounters at least one genuinely new center-4 wall;
6. the current lazy oracle also encounters latent older walls in each branching
   case, but this is **not** interpreted as minimum-representation necessity; and
7. Phase 9C / the independent full-stratum red team are required before any
   queried wall is called a necessary completion primitive.

Proof map
---------
1. ``test_center4_local_semantics_confirm_pressure_roles_and_record_lazy_wall_trace``
   runs the lazy event-order oracle on only the nine Phase-9A pressure cells,
   checks the exact uniform/branching roles, witness reindex behavior, the
   seven-by-three task profile, and records the new/latent queried-wall trace.

Boundary
--------
The queried-wall set is an algorithm trace, not a minimum completion support.
In particular, a latent older wall touched by this oracle may be eliminated by a
smaller task-relative representation.  Phase 9C subsequently does exactly that:
all seven task-minimal completions collapse to one genuinely new center-4 wall.

The exact task multiplicity statement is independently red-teamed by local full
center-4 stratum refinement in
`sonnet/lonely-runner/python/center4_local_full_oracle.py`; the independent
oracle agrees with the lazy task set on all nine pressure cells.

No new Lonely Runner theorem, public constraint-cell API, or discrete observer
connection is established.

References
----------
[Sungkawichai-Trakulthongchai-2026] Touch Sungkawichai, Tanupat
Trakulthongchai, "Eleven, twelve, and thirteen lonely runners,"
arXiv:2604.23906 (2026), https://arxiv.org/abs/2604.23906 .
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import sys

import pytest


RUN_FULL = os.environ.get("AEG_RUN_LR_CENTER4_SEMANTICS") == "1"
pytestmark = pytest.mark.skipif(
    not RUN_FULL,
    reason="opt-in Sonnet 001 center4 local semantic red team",
)


def _load_module():
    root = Path(__file__).parents[2]
    script_dir = root / "sonnet" / "lonely-runner" / "python"
    script_path = script_dir / "center4_semantic_redteam.py"
    sys.path.insert(0, str(script_dir))
    try:
        spec = importlib.util.spec_from_file_location(
            "sonnet_center4_semantic_redteam",
            script_path,
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(script_dir))


def test_center4_local_semantics_confirm_pressure_roles_and_record_lazy_wall_trace():
    semantic = _load_module()
    result = semantic.analyze_center4_semantic_redteam()

    assert len(result.cases) == 9
    assert len(result.uniform_cases) == 2
    assert len(result.branching_cases) == 7
    assert sorted(case.task_count for case in result.branching_cases) == [3] * 7

    assert all(
        case.phase9a_role == "nonbranching-pressure"
        for case in result.uniform_cases
    )
    assert all(case.same_boundary_and_mode for case in result.uniform_cases)
    assert all(
        case.new_tasks[0][0] - case.old_task[0] == 2
        for case in result.uniform_cases
    )

    assert all(
        case.phase9a_role == "completion-pressure"
        for case in result.branching_cases
    )
    assert all(case.new_center4_walls for case in result.branching_cases)
    # This is intentionally a trace assertion, not a necessity claim.  Phase 9C
    # eliminates these latent older queries from every minimum support.
    assert all(case.latent_older_walls for case in result.branching_cases)
