"""Sonnet 001 Phase 9A: freeze persistent constraint cells before center-4 scaling.

Question
--------
Can the center-2 -> center-3 representation method be carried forward without
silently changing its local effect detector or reconstructing the full center-3
wall arrangement?

Two checks are required.  First, a generalized persistent-cell formulation of
the detector must reproduce the already frozen center-2 -> center-3
`841 / 2 / 6` partition exactly, not merely approximately.  Only then may the
same detector be applied unchanged to the Phase-8E center-3 representation and
the newly admitted center-4 contact layer.

Primitive data
--------------
The program receives:

- the exact center-2 full pair-difference cells and the 21 center-2
  task-relevant predicates;
- the seven center-3 completion walls frozen by Phase 8C;
- the six Phase-8C.2 completion decoders and two Phase-8B history-reindex task
  updates;
- the exact Phase-8E joint representation semantics;
- the center-4 enter/exit contact events generated by the same A/M contact law.

It does not receive the 72,241-state complete center-3 arrangement, any complete
center-4 arrangement, center-4 task labels, a center-4 fresh tree, deeper contact
layers, or `K=13` data.

Classical lineage
-----------------
The surrounding Lonely Runner computational frontier is described in
[Sungkawichai-Trakulthongchai-2026].  Difference constraints and finite exact
search are implementation backends here; the persistent constraint-cell
objectification and its role in process refinement are **Shakespeare
interpretations**, not claims of the classical source.

Shakespeare reconstruction
---------------------------
A persistent cell stores

    current task semantic
    + current predicate signature
    + a finite union of exact multiplicative difference-constraint closures.

For center 3 the current predicate signature is exactly the Phase-8E
`21 old + 7 new` language.  Exact center-2 cells are refined only by those seven
walls, yielding 2,753 current cells with 75 task semantics.  The closure atoms
retain process provenance without adding omitted center-3 wall coordinates.

A generic next-layer detector uses only the cell closures, current first-witness
semantic, old contact events, and newly admitted contact events.  It implements
the same two Phase-8 local pressures:

- a new event can be forced at/before the current witness;
- a genuinely new contact wall can cross the old causal prefix while its side is
  unresolved by the current exact constraints.

The detector is first replayed on fully resolved center-2 cells.  Only after
exact set equality with Phase 8 is established is it applied unchanged to
center-3 cells and center-4 events.

Calibration statement
---------------------
Passing this bounded scaling calibration certifies that:

1. the generic persistent-cell detector reproduces the exact frozen center-2 ->
   center-3 sets: 841 stable, 2 nonbranching-pressure, and 6
   completion-pressure parents;
2. the Phase-8E center-3 representation materializes as exactly 2,753 persistent
   cells with 75 current task semantics;
3. those cells retain 13,609 exact closure atoms, with no hidden full center-3
   census added by the materialization;
4. the unchanged detector applied to center-3 -> center-4 marks exactly 2,744
   cells stable, 2 cells with nonbranching pressure, and 7 cells with completion
   pressure;
5. only 9 of 2,753 current cells are therefore reopened by the first frozen-rule
   center-4 pressure pass; and
6. the two nonbranching cases remain **uninterpreted pressure** at this stage:
   the test does not call them observer transport or history reindex before a
   Phase-9B semantic red team.

Proof map
---------
1. ``test_persistent_cell_detector_replays_phase8_and_exposes_sparse_center4_pressure``
   materializes the center-2 and center-3 cell representations, checks exact
   center-2 set equality against Phase 8, and then checks the frozen-rule
   center-3 -> center-4 pressure counts and representation sizes.

Boundary
--------
The center-3 persistent cells are unions of exact closure atoms rather than a
claim that each task cell is one convex difference-constraint region.  The
center-4 result is a **pressure classification**, not yet a semantic
classification of the refined children.  In particular, `2 nonbranching` does
not establish a nonempty discrete resonant/transport sector.

The detector uses a causal-envelope formulation on partially materialized
center-3 cells.  Its legitimacy for scaling rests on the exact center-2 replay
certificate in this same file; center-4 semantics must still red-team the
predicted roles before promotion.

References
----------
[Sungkawichai-Trakulthongchai-2026] Touch Sungkawichai, Tanupat
Trakulthongchai, "Eleven, twelve, and thirteen lonely runners,"
arXiv:2604.23906 (2026), https://arxiv.org/abs/2604.23906 .
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path
import sys

import pytest


RUN_FULL = os.environ.get("AEG_RUN_LR_CENTER4_CELLS") == "1"
pytestmark = pytest.mark.skipif(
    not RUN_FULL,
    reason="opt-in Sonnet 001 center4 persistent-cell scaling calibration",
)


def _load_module():
    root = Path(__file__).parents[2]
    script_dir = root / "sonnet" / "lonely-runner" / "python"
    script_path = script_dir / "persistent_constraint_cells.py"
    sys.path.insert(0, str(script_dir))
    try:
        spec = importlib.util.spec_from_file_location(
            "sonnet_persistent_constraint_cells",
            script_path,
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(script_dir))


def test_persistent_cell_detector_replays_phase8_and_exposes_sparse_center4_pressure():
    cells = _load_module()

    calibrated = cells.calibrate_center2_detector()
    assert len(calibrated.stable) == 841
    assert len(calibrated.nonbranching_pressure) == 2
    assert len(calibrated.completion_pressure) == 6

    current, partition = cells.probe_center3_to_center4_pressure()
    assert len(current) == 2_753
    assert len({cell.task for cell in current}) == 75
    assert sum(len(cell.atoms) for cell in current) == 13_609
    assert sum(cell.provenance_count for cell in current) == 13_609

    assert len(partition.stable) == 2_744
    assert len(partition.nonbranching_pressure) == 2
    assert len(partition.completion_pressure) == 7
    assert len(partition.affected) == 9
