"""Sonnet 001 Phase 10: center-5 no-op and infinite contact-tail closure.

Question
--------
After Phase 9D materializes a 29-predicate center-4 persistent representation,
does the next contact layer force another representation update?  If not, can a
finite exact certificate prove that *all* later contact centers are irrelevant
to the current first-witness task rather than checking centers one by one?

Primitive data
--------------
The program receives:

- the certified Phase-9D center-4 representation: 3,067 persistent cells,
  81 task semantics, and 14,967 exact closure atoms;
- the unchanged next-layer pressure detector;
- center-5 contact events generated by the same four-runner A/M contact law;
- positivity of the runner speeds already built into the relative-speed domain.

It does not receive center-5 task labels, a center-5 tree, any center-6-or-later
wall arrangement, deeper-layer completion primitives, or `K=13` data.

Classical lineage
-----------------
The underlying event times are elementary positive-speed linear scalings.  The
finite-certificate / infinite-tail interpretation is a **Shakespeare
reconstruction** of the process representation rather than a claim attributed
to an external theorem.  The surrounding Lonely Runner frontier is described in
[Sungkawichai-Trakulthongchai-2026].

Shakespeare reconstruction
---------------------------
First apply the frozen Phase-9A detector to center 4 -> center 5.  It marks all
3,067 current cells stable.

Then red-team that zero-pressure result directly.  For every exact closure atom,
compare every newly admitted center-5 enter/exit event with the current certified
first-witness boundary.  All 119,736 comparisons must be strictly later, with no
earlier/equal and no unresolved case.

Finally observe that for a fixed runner and every contact event with center
`n >= 5`,

    alpha(n, kind) >= alpha(5, enter) = 5 - delta = 24/5.

Because every runner speed is positive, its center-5 enter event is the earliest
event in the entire infinite tail.  It is therefore sufficient to certify the
59,868 `closure atom x runner` anchor comparisons at center-5 enter.  If all are
strictly later than the current witness, every event at every center `n >= 5` is
strictly later as well.

Calibration statement
---------------------
Passing this bounded-but-infinite-tail calibration certifies that:

1. the Phase-9D center-4 state has exactly 3,067 cells, 81 task semantics, and
   14,967 exact closure atoms;
2. the unchanged center-4 -> center-5 pressure detector returns
   `3,067 stable / 0 nonbranching / 0 completion`;
3. direct semantic comparison of all eight center-5 events on all closure atoms
   gives exactly 119,736 strict-later comparisons, zero earlier/equal and zero
   unresolved comparisons;
4. the four center-5-enter anchor events give exactly 59,868 strict-later
   comparisons, again with zero earlier/equal and zero unresolved cases;
5. `alpha(5,enter)=24/5`, and every event at every integer center `n >= 5` has
   coefficient at least this large for the same runner; and
6. consequently the finite 29-predicate center-4 representation is sufficient
   for the first-witness semantics of the entire infinite remaining contact
   alphabet in this four-runner calibration.

Proof map
---------
1. ``test_center5_pressure_and_direct_semantics_are_exact_noops`` checks the
   frozen detector and all 119,736 direct center-5 event/witness comparisons.
2. ``test_center5_enter_anchor_closes_the_entire_infinite_contact_tail`` checks
   the 59,868 anchor comparisons and the exact monotone tail coefficient rule.

Boundary
--------
The infinite-tail conclusion is about the **first-witness contact semantics** of
this four-runner process model inside the declared relative-speed domain.  It is
not a proof of the Lonely Runner conjecture, not a statement about other runner
counts, and not a universal theorem that finite Shakespeare presentations always
stabilize.

The closure also does not mean the 14,967 exact provenance atoms are a public
ontology.  They are the certificate backend used to prove that no omitted future
event can intervene.  Phase 9C already showed that solver/certificate provenance
can be strictly richer than the task-minimal visible representation.

References
----------
[Sungkawichai-Trakulthongchai-2026] Touch Sungkawichai, Tanupat
Trakulthongchai, "Eleven, twelve, and thirteen lonely runners,"
arXiv:2604.23906 (2026), https://arxiv.org/abs/2604.23906 .
"""

from __future__ import annotations

from fractions import Fraction
import importlib.util
import os
from pathlib import Path
import sys

import pytest


RUN_FULL = os.environ.get("AEG_RUN_LR_INFINITE_TAIL") == "1"
pytestmark = pytest.mark.skipif(
    not RUN_FULL,
    reason="opt-in Sonnet 001 infinite contact-tail closure calibration",
)


def _load(name: str, filename: str):
    root = Path(__file__).parents[2]
    script_dir = root / "sonnet" / "lonely-runner" / "python"
    script_path = script_dir / filename
    sys.path.insert(0, str(script_dir))
    try:
        spec = importlib.util.spec_from_file_location(name, script_path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(str(script_dir))


def test_center5_pressure_and_direct_semantics_are_exact_noops():
    pressure = _load("sonnet_center5_pressure", "center5_pressure.py")
    noop = _load("sonnet_center5_semantic_noop", "center5_semantic_noop.py")

    cells, partition = pressure.analyze_center5_pressure()
    assert len(cells) == 3_067
    assert len({cell.task for cell in cells}) == 81
    assert sum(len(cell.atoms) for cell in cells) == 14_967
    assert len(partition.stable) == 3_067
    assert len(partition.nonbranching_pressure) == 0
    assert len(partition.completion_pressure) == 0

    result = noop.analyze_center5_semantic_noop()
    assert (result.cells, result.tasks, result.atoms) == (3_067, 81, 14_967)
    assert result.new_events_per_atom == 8
    assert result.strict_later_comparisons == 119_736
    assert result.earlier_or_equal_comparisons == 0
    assert result.unresolved_comparisons == 0
    assert result.affected_cells == 0
    assert result.unresolved_cells == 0


def test_center5_enter_anchor_closes_the_entire_infinite_contact_tail():
    tail = _load(
        "sonnet_infinite_contact_tail_closure",
        "infinite_contact_tail_closure.py",
    )
    result = tail.analyze_infinite_contact_tail_closure()

    assert (result.cells, result.tasks, result.atoms) == (3_067, 81, 14_967)
    assert result.runners == 4
    assert result.anchor_center == 5
    assert result.anchor_kind == "enter"
    assert result.anchor_alpha == Fraction(24, 5)
    assert result.strict_anchor_comparisons == 59_868
    assert result.earlier_equal_anchor_comparisons == 0
    assert result.unresolved_anchor_comparisons == 0

    assert tail.future_alpha_offset(5, "enter") == 0
    assert tail.future_alpha_offset(5, "exit") == Fraction(2, 5)
    for center in (6, 7, 13, 100):
        assert tail.future_alpha_offset(center, "enter") > 0
        assert tail.future_alpha_offset(center, "exit") > 0
