"""AEG Shakespeare: process-representation discovery library."""

from .construction import (
    PrimitiveConstruction,
    PrimitiveProposal,
    PrimitiveProposalResult,
    RejectedPrimitiveProposal,
    SymbolicOperation,
    generate_primitive_proposals,
)
from .core import (
    ProcessSystem,
    ProcessWord,
    SearchBudget,
    homogeneous_monomials,
    interpret_history,
)
from .cost import PresentationCost
from .grammar import (
    GeneratedGrammar,
    GeneratedPresentation,
    discover_generated_grammar,
    discover_generated_presentation,
)
from .history_geometry import (
    BoundaryProfile,
    PrefixCode,
    PrefixCodeMetrics,
    boundary_profile,
    history_depth,
    huffman_prefix_code,
)
from .linear import KrylovReturnRelation, discover_krylov_relation
from .relations import (
    ProcessPolynomialRelation,
    RelationDecomposition,
    RelationKernel,
    ReturnRelation,
    action_matrix,
    coefficient_vector,
    decompose,
    discover_operator_relation,
    discover_relation_decomposition,
    discover_relation_kernel,
    discover_return_relation,
    factor_process_relation,
)
from .rewrite import (
    RewriteResult,
    RewriteStep,
    WordRewriteRule,
    normalize_word,
    rewrite_once,
)
from .search import (
    ExactReconstructionPresentation,
    PresentationCandidate,
    PresentationSearchResult,
    evaluate_exact_reconstruction_presentation,
    pareto_frontier,
    search_exact_reconstruction_presentations,
    structural_exact_reconstruction_cost,
)
from .signature import (
    ProcessJetSignature,
    enumerate_process_words,
    histories_task_equivalent,
    history_process_jet_signature,
    process_jet_signature,
    signatures_equivalent,
)

__all__ = [
    "PrimitiveConstruction",
    "PrimitiveProposal",
    "PrimitiveProposalResult",
    "RejectedPrimitiveProposal",
    "SymbolicOperation",
    "generate_primitive_proposals",
    "ProcessSystem",
    "ProcessWord",
    "SearchBudget",
    "homogeneous_monomials",
    "interpret_history",
    "PresentationCost",
    "GeneratedGrammar",
    "GeneratedPresentation",
    "discover_generated_grammar",
    "discover_generated_presentation",
    "BoundaryProfile",
    "PrefixCode",
    "PrefixCodeMetrics",
    "boundary_profile",
    "history_depth",
    "huffman_prefix_code",
    "KrylovReturnRelation",
    "discover_krylov_relation",
    "ProcessPolynomialRelation",
    "RelationDecomposition",
    "RelationKernel",
    "ReturnRelation",
    "action_matrix",
    "coefficient_vector",
    "decompose",
    "discover_operator_relation",
    "discover_relation_decomposition",
    "discover_relation_kernel",
    "discover_return_relation",
    "factor_process_relation",
    "RewriteResult",
    "RewriteStep",
    "WordRewriteRule",
    "normalize_word",
    "rewrite_once",
    "ExactReconstructionPresentation",
    "PresentationCandidate",
    "PresentationSearchResult",
    "evaluate_exact_reconstruction_presentation",
    "pareto_frontier",
    "search_exact_reconstruction_presentations",
    "structural_exact_reconstruction_cost",
    "ProcessJetSignature",
    "enumerate_process_words",
    "histories_task_equivalent",
    "history_process_jet_signature",
    "process_jet_signature",
    "signatures_equivalent",
]

__version__ = "0.0.1"
